### ISSUE TITLE
Settings: Make refresh interval user configurable

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1027]
### 📝 Provide a description of the new feature

_Created based on discussion within https://github.com/gitify-app/gitify/pull/1014_

Currently we refresh notifications every minute (60000 milliseconds).

This FR is to make this user configurable, perhaps via a predefined set of values

**Comment by setchy** [comment]
To get the ball rolling, what would be a set of useful intervals?

**Comment by adufr** [comment]
Mmh, probably something like 30s, 1mn, 2mn, 5mn (and probably a tooltip to inform the user about rate limits?)

**Comment by afonsojramos** [comment]
Are we sure that this is a feature we want?

**Comment by bmulholland** [comment]
Or at least, what's the motivation for it? What problem is it solving?

**Comment by adufr** [comment]
I've always had this feature in mind but I knew that everyone would not agree with it 😬

IMO this allows 2 things:
- if you increase the interval -> you reduce the risk of reaching GitHub API rate limits
- if you reduce the interval -> you're able to be even more reactive on notifications 😅 

But I do agree that this really is a "power-user" setting, that would only benefit very few users...

**Comment by afonsojramos** [comment]
Alright, let's close this issue then. We can always re-open in the future if necessary
