### ISSUE TITLE
Feature Request: Option to specify which browser the links are sent to

### ISSUE THREAD

**Issue by niclake** [gitify-app/gitify#1117]
### 📝 Provide a description of the new feature

Today, when clicking a notification or alert from the app, it always opens in the system default browser. I would love to have the option to choose a different browser to have these links sent to.

Use case: 99% of my notifications are from my jobby job, and I use Chrome as my browser for everything related to that, while using Safari as my default browser. I'd love to be able to tell Gitify to send everything to Chrome by default.

Bonus 1: an option to copy the URL of the notification (i.e. the PR URL for a pull request notification)

Bonus 2: a per-org option for browsers (i.e. send everything from my org to Chrome, but send anything relating to my personal repos to Safari)

**Comment by afonsojramos** [comment]
I think this is out of scope for this project. There are a million tools that open different browsers based on the site that you give it for all platforms, so I'd suggest using that instead.
