### ISSUE TITLE
Response caching with conditional requests

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1124]
### 📝 Provide a description of the new feature

Add response caching so that we can enable additional features (ie: [show read notifications](https://github.com/gitify-app/gitify/pull/1052), [fetch >50 (all) notifications](https://github.com/gitify-app/gitify/issues/356)) without the concerns of being rate-limited.

[Using conditional requests](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#use-conditional-requests-if-appropriate) should be sufficient, which requires us to store and use response `etag` or `last-modified` headers in subsequent `GET` requests to the same resource.

Changes required to https://github.com/gitify-app/gitify/blob/main/src/utils/api/request.ts

**Comment by dammy95** [comment]
Hi @setchy 👋🏾  – I can look into this. I'll do some research and do a small write-up for you to review before I start. Let me know if that works for you 😄

**Comment by dammy95** [comment]
Hey @setchy – I have some options on how we can implement this:

1) Using [axios-cache-interceptor](https://axios-cache-interceptor.js.org/). Here's a [good read by its author](https://arthur.place/implications-of-cache-or-state/). This creates an axios interceptor that adds the etag (or last-modified) headers to the request and return the appropriate response.

2) Implement step 1) above without the axios-cache interceptor library, using localStorage to store the cached response.

Somehow I sense that I could be overcomplicating the implementation? Let me know what you think, thanks!

**Comment by setchy** [comment]
Great research @dammy95.

I don't have a strong view on the best way to implement this. Happy to try and few things and adapt as we move forward

**Comment by afonsojramos** [comment]
We're already using axios, so I'd suggest taking advantage of that and its large community! Easy solutions are usually the best ones 😁🚀

**Comment by setchy** [comment]
The other option would be to go down this route https://github.com/gitify-app/gitify/issues/823

**Comment by afonsojramos** [comment]
@setchy how does that tackle this issue? Do they have built-in caching or something into their client?

**Comment by setchy** [comment]
> @setchy how does that tackle this issue? Do they have built-in caching or something into their client?

They sure do

**Comment by afonsojramos** [comment]
Alright!!! Then that looks like a great solution to me 🚀 

@dammy95, as the person assigned to the issue, is that okay with you?

**Comment by dammy95** [comment]
Yupp that sounds great to me @afonsojramos @setchy  – I'll look in to the octokit refactor solution and create a PR for review 🚀

**Comment by setchy** [comment]
I guess there is also the option of using react-query (or similar) - https://www.welcomedeveloper.com/posts/managing-cache-react-query/

**Comment by afonsojramos** [comment]
Might be the most extensible (and widely-used) option honestly, don't know how I forgot about that one 😬

**Comment by setchy** [comment]
Another library I saw this week - https://github.com/alexcambose/custom-cache-decorator

**Comment by Araxeus** [comment]
Could also completely replace axios with https://www.npmjs.com/package/make-fetch-happen

**Comment by akellbl4** [comment]
[Notifications are fetched by an interval](https://github.com/gitify-app/gitify/blob/main/src/context/App.tsx#L148) which is not ideal, because if the connection is slow requests can stack and make multiple requests at once.

I'm not familiar with the way electron runs timing functions, but a better way would be to use `setTimeout` recursively. So when a request is finished a new timeout is started.

As an alternative, I can suggest using [react-query](https://tanstack.com/query/v4/docs/framework/react/overview) which handles caching, retries, interval fetching, and request deduplication. Unless it was considered and didn't fit the project.
