### ISSUE TITLE
Settings page goes white blank

### ISSUE THREAD

**Issue by MichalMichalak** [gitify-app/gitify#1130]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Settings page won't load up, showing white blank page instead. Unable to interact with app after that, but can reload the page. What I've noticed, there's exception in `Settings.tsx` and the app is calling github.com API and fails.

Console shows exception:
`Settings.tsx:310 Uncaught TypeError: Cannot read properties of null (reading 'login')`

Call to github ends with 401 Unauthorized.
```
Request URL: https://api.github.com/
Request Method: GET
Status Code: 401 Unauthorized
```

### 🪜 Steps To Reproduce

1. Log in to EGH with token. (TBH I am not sure you can log in, I'm already logged in and can't logout. I assume logout button is somewhere in the settings.)
2. Click settings ⚙️ icon.
3. Page not loading, app becomes white blank.

### Gitify Version

5.5.0

### Operating System

macOS

### GitHub Account

GitHub Enterprise

### 📸 Screenshots

![Screenshot 2024-05-22 at 9 59 13](https://github.com/gitify-app/gitify/assets/3244285/70335181-e5dc-4a5e-98c0-ec14bce10b34)

**Comment by MichalMichalak** [comment]
@setchy Thanks a ton for solving it. Is there any dev build I could use to enter the settings?

**Comment by setchy** [comment]
v5.6.0 is hot off the press. LMK how that goes for you

**Comment by MichalMichalak** [comment]
Fixed. Thank you. 🙇
