### ISSUE TITLE
Not getting notifications from private repos

### ISSUE THREAD

**Issue by mrcasals** [gitify-app/gitify#1136]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

After upgrading to v5.5.0, and regenerating the PAT using the default values provided by Gitify, I'm not recieving notifications from private repos.

### 🪜 Steps To Reproduce

Generate the PAT using the default values provided by Gitify. I'm not receiving anything

### Gitify Version

5.5.0

### Operating System

macOS

### GitHub Account

GitHub.com

**Comment by setchy** [comment]
@mrcasals - was this previously working?  

Are you seeing these private repository notifications within https://github.com/notifications?

I cannot see anything within the GitHub PAT (classic) scopes settings that would be restricting private repositories

**Comment by mrcasals** [comment]
It was working fine previously, yup! And I'm getting the notifications in the GitHub UI 😊 Sorry for not being clear on this 🙏

**Comment by setchy** [comment]
@mrcasals - could you please check the response of the GitHub Notifications REST API
* https://api.github.com/notifications?participating=false
* https://api.github.com/notifications?participating=true

The only query parameter we pass through is based upon your `Show only participating` Gitify Settings

**Comment by mrcasals** [comment]
Sigh, apparently the API doesn't give me any notification from the private repos I'm interested into, I guess the organization changed some configuration, because even if I try to get the read ones with `https://api.github.com/notifications?all=true` I get none (even though I can see them in the UI).

So it might be related to my organization settings. Thanks for the support, and sorry for taking your time!

I'll close this issue then.

**Comment by setchy** [comment]
No problems at all.  I've added this scenario to https://github.com/gitify-app/gitify/issues/890.  

If you do happen to find a public API that returns private notifications, then we can look to support it.
