### ISSUE TITLE
introduce branded types

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1141]
### 📝 Provide a description of the new feature

https://egghead.io/blog/using-branded-types-in-typescript

Could be useful for types such as `URL`, `Hostname`, `Token`, `ClientID`, `ClientSecret` etc

**Comment by dammy95** [comment]
Hi @setchy – I'm currently looking into this, but wanted to validate my initial approach before I start properly. Here is my current plan below:

1) Create Branded Types for `URL` `Hostname`, `Token`, `ClientID`, `ClientSecret`.  The base types for all 4 items should be of type `string`. 
2) The branded types can then be added to the `types.js` file in the `src` directory.
3) Taking `hostname` as an example here, we would replace all occurrences of `hostname: string` with `hostname: Hostname` (where `Hostname` will be a new branded type).
4) Repeat step 3 for `URL`, `Token`, `ClientID`, and `ClientSecret`

Let me know if you have any additions (or subtractions) to this approach 😄

**Comment by setchy** [comment]
hi @dammy95 - well summarized.  That's what I had in mind :)

**Comment by dammy95** [comment]
Perfect – I'll get started on this then 👍🏾
