### ISSUE TITLE
Header expands to fill entire panel

### ISSUE THREAD

**Issue by nicholas-ochoa** [gitify-app/gitify#1157]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I recently updated from a build that was about six months old, to version 5.6.0 and noticed when there are just a few notifications, there is a header with the text `api.github.com` that expands to fill all remaining space pushing the notifications down to the bottom of the panel (see screenshot).

If I have more notifications open the header area takes up less space and will expand each time I mark a notification as read.

### 🪜 Steps To Reproduce

1. Have a couple notifications, but not enough to fill the panel
2. Open Gitify, notice that the header is taking up most of the space.

### Gitify Version

5.6.0

### Operating System

macOS

### GitHub Account

GitHub.com

### 📸 Screenshots

<img width="503" alt="image" src="https://github.com/gitify-app/gitify/assets/126299/5b96ddc8-a1cc-46da-9f6d-c2efef582511">

**Comment by nicholas-ochoa** [comment]
No, just one account. That made me think to uncheck `Show account hostname` in settings, which seems to have fixed it for me. Thank you!

<img width="249" alt="image" src="https://github.com/gitify-app/gitify/assets/126299/44249f3a-0276-47f5-a1a6-ae2015b50031">

**Comment by setchy** [comment]
> No, just one account. That made me think to uncheck `Show account hostname` in settings, which seems to have fixed it for me. Thank you!
> 
> <img width="249" alt="image" src="https://github.com/gitify-app/gitify/assets/126299/44249f3a-0276-47f5-a1a6-ae2015b50031">
> 

Great to hear. 

We're further reworking the Accounts module in the upcoming release. I hadn't noticed this UI issue myself, but will keep an eye out for it.
