### ISSUE TITLE
Gitify open on middle of double screen on Windows

### ISSUE THREAD

**Issue by camille-avatarmedical** [gitify-app/gitify#1162]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

When first opened Gitify open somewhere in the middle of my 2 screens on my Windows 11 dual screen setup, as you can see in the picture below:

![image](https://github.com/gitify-app/gitify/assets/160714555/cb98d552-7f36-430b-b98b-c43ddb24eddf)

For some reason if I minimize it and open it again it is where it should (on top on the Windows bar, above the notification area, aka bottom right corner on my primary screen)

Here is my dual screen setup:

![image](https://github.com/gitify-app/gitify/assets/160714555/3ed6d8e3-4e86-4a8e-950a-739b07805b63)

For details this rather a 3x screen setup where both screen (1 and 3) are duplicated. This is because I have a laptop that sit somewhere and 2 standalone monitor on my desk. Every monitor is running at 1920x1080. There are different refresh rate for what it worth.

### 🪜 Steps To Reproduce

1. Have a dual screen setup as described in the description.
2. Open Gitify

### Gitify Version

5.6.0

### Operating System

Windows

### GitHub Account

GitHub.com

**Comment by setchy** [comment]
Closing as should be resolved in #1193

**Comment by setchy** [comment]
Reported as still occurring in 5.8.1

**Comment by setchy** [comment]
@camille-avatarmedical  - this looks like a potential fix

https://github.com/max-mapper/menubar/issues/435#issuecomment-1581628798

**Comment by setchy** [comment]
I've raised an upstream fix 🤞 https://github.com/max-mapper/menubar/pull/479

**Comment by setchy** [comment]
@camille-avatarmedical - would appreciate if you could test this pre-release build: https://github.com/gitify-app/gitify/actions/runs/9538457506 🙏
