### ISSUE TITLE
(MacOS) Gitify icon not visible in tray

### ISSUE THREAD

**Issue by adufr** [gitify-app/gitify#1229]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Hi, I just upgraded from 5.5.0 to 5.8.0, and I the Gitify icon is now impossible to see in my tray because it's a black image on a black background

idk in which version the bug appeared as I skipped a few updates

(+ the issue template doesn't include version 5.8.0 yet, so I couldn't select it)

### 🪜 Steps To Reproduce

1. Install/open Gitify 5.8.0 on a Mac
2. Open any app in fullscreen so that the MacOS tray is black
3. Make sure you don't have any notifications (otherwise the icon is green)

### Gitify Version

5.8.0

### Operating System

macOS

### GitHub Account

GitHub.com

### 📸 Screenshots

<img width="454" alt="image" src="https://github.com/gitify-app/gitify/assets/26418696/41200054-24f4-440c-91fe-c9575f127da2">

**Comment by setchy** [comment]
Good catch @adufr - I've never noticed that when using macOS dark mode AND full-screening an app turns the menubar completely black. 

I can't think of any changes which would have caused this.  To confirm, you're saying this worked on v5.5.0?

**Comment by setchy** [comment]
I can confirm this bug exists on `5.7.0` as I haven't yet updated one of my machines...

**Comment by adufr** [comment]
> I can't think of any changes which would have caused this. To confirm, you're saying this was working on v5.5.0?

Well I'm 99% sure it did (it instantly caught my eye when I upgraded, so I really don't think this was the case before); but I didn't try downgrading

**Comment by danosier** [comment]
> My icon was white in 5.7.0. I updated to 5.8.0 today and the Gitify icon in the menu bar is black for me

I should add additional context. Multi display setup and using macOS dark mode. Gitify's appearance is set to "System", but toggling it between the 3 options seems to change nothing, black icon on all three. Icon is not "invisible for me, but definitely hard to see

![Screenshot 2024-06-13 at 3 06 55 PM](https://github.com/gitify-app/gitify/assets/16171678/a1481641-367b-49b3-b957-5673d42379a9)

**Comment by setchy** [comment]
Fixed in 5.8.1 - thank you all for quickly raising the issue 🙇

**Comment by adufr** [comment]
Thanks for the quick fix/release :)
