### ISSUE TITLE
Chevron on repository header to collapse all notifications

### ISSUE THREAD

**Issue by Araxeus** [gitify-app/gitify#1243]
### 📝 Provide a description of the new feature

A way to collapse (hide) all notifications from a specific repository, while keeping the repository header

maybe something like this:
![image](https://github.com/gitify-app/gitify/assets/78568641/ac800d91-9e84-412a-8916-23d71b1adc2d)

**Comment by setchy** [comment]
We have something like this at the `account` level - so would be easy to implement.

Biggest question is where should the `chevron` be positioned 🤔

**Comment by Araxeus** [comment]
> Biggest question is where should the chevron be positioned

IMO it should be either far left or far right

**Comment by setchy** [comment]
Yes....

our `accounts` collapse chevron is far right.  but for repository headers we show the `mark as read` and `mark as done` on hover in that space 🤔

**Comment by Araxeus** [comment]
I think the chevron should always be shown (atleast if its collapsed), so maybe just place it on the far left like in my screenshot?

should probably be optional too
