### ISSUE TITLE
Custom Scrollbar

### ISSUE THREAD

**Issue by Araxeus** [gitify-app/gitify#1244]
### 📝 Provide a description of the new feature

The default scrollbar on Windows is very ugly when using a dark theme
![image](https://github.com/gitify-app/gitify/assets/78568641/a1c63b24-1417-42be-9940-6d7169ce3c4d)

would be nice to have a custom scrollbar that conforms to the theme

**Comment by setchy** [comment]
@Araxeus - good suggestion.  out of interest - which version of gitify are you using? 

Just wanted to check that this update #1220 in 5.8.0 didn't affect this

**Comment by Araxeus** [comment]
I have just updated to v5.8.1
