### ISSUE TITLE
Scrollbars visibility

### ISSUE THREAD

**Issue by afonsojramos** [gitify-app/gitify#1257]
Scrollbars are now permanently visible on macOS when there is overflow content. Previously they would hide/show based on scrolling activity.

If possible, let's try to improve this!

<img width="501" alt="Screenshot 2024-06-17 at 7 41 43 AM" src="https://github.com/gitify-app/gitify/assets/386277/f1bff16d-e8ff-4cf0-b109-372c23243479">
<img width="500" alt="Screenshot 2024-06-17 at 7 40 26 AM" src="https://github.com/gitify-app/gitify/assets/386277/251d5941-ca74-4af5-a415-c79b93a179aa">

_From the comment by @setchy in https://github.com/gitify-app/gitify/issues/1253#issuecomment-2173166188_

**Comment by Araxeus** [comment]
isnt this actually a good thing? that way the user know there is more content that can be scrolled to?

anyways if you want the scrollbar css to be platform specific, then a tag in the html with the platform could be useful
i.e `<html class="dark" platform="windows">...`

**Comment by afonsojramos** [comment]
> isnt this actually a good thing? that way the user know there is more content that can be scrolled to?

To be honest... yeah... @setchy thoughts?

**Comment by setchy** [comment]
I agree - it now provides clarity over the additional content.  was just sharing the observation 😎
