### ISSUE TITLE
Auto-unsub of merged/closed PRs

### ISSUE THREAD

**Issue by y-nk** [gitify-app/gitify#1317]
### 📝 Provide a description of the new feature

In the setting, there should be a checkbox to enable the feature. When enabled, the feature should auto-unsubscribe PRs which have been merged or closed automatically.

### ➕ Additional Information

I understand this is a bit on the edge of gitify, so i wouldn't be surprised it it's rejected. That being said, the frequent pull mechanism of notifications + the existing "unsubscribe" button looks like making it a cheap feature to implement.

- [x] I'm willing to help and implement the feature if agreed on the scope.

**Comment by bmulholland** [comment]
Yeah, this feels outside the project's goals to me :)

https://github.com/gitify-app/gitify/blob/main/CONTRIBUTING.md#project-philosophy

**Comment by setchy** [comment]
@y-nk have you seen our upcoming **filters** feature - #? 

Perhaps filtering on notification type and/or state could be a middle ground?

**Comment by y-nk** [comment]
@setchy it's gonna help on the ui level but i'll be frank this is clearly for the sake of maintaining a clean state at GitHub level. I'd love to have submitted this to them directly but the chances they ever see my feat request are already lower than low ; chances to have them backlog it, prioritize it, implemented and released... well... let's put it nicely: it's a big organisation.

Since i use Gitify since about forever i thought it'd be a great place to get this done ; I'm sure some user would love it (probably the same who use the unsub button). I know the team is smaller and friendlier, so at least I got an audience ✌️ but yeah, the unsubscribe button was already at the edge, having automation around it seems pushing this edge another mile above scope 🥲

thanks for considering anyhow @bmulholland 🙏

**Comment by afonsojramos** [comment]
@y-nk Unless we create a sort of "automations" section, I agree with @bmulholland. Might be an idea for the future. But not sure if there are enough useful automations to justify such a thing.

I'd definitely opt out of this one though. What if someone wants to re-spark a conversation on an old PR (even though it might not be the best place for it)?

**Comment by y-nk** [comment]
@afonsojramos indeed an automation would be nice. tbh if automation is there, i'd rather have Github implement "user based triggers" in GHA, but this is definitely off-topic :D

I'll close this as there's no further debate imho. I thought that proposing to implement it all would have been enough appeal to include this as "it's a 0 cost" but I understand your standpoint that is not in the roadmap or interest of the app overall.

Thanks for the time spent on this 🙏
