### ISSUE TITLE
Rate Limited

### ISSUE THREAD

**Issue by pedro-mass** [gitify-app/gitify#1325]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Not sure if I'm popular, or what, but it seems I keep hitting the Rate Limited page pretty often
Is there a way to expand the limit?

I have a token dedicated specifically to Gitify

### 🪜 Steps To Reproduce

unknown

### Gitify Version

5.9.0

### Operating System

Windows

### GitHub Account

GitHub Cloud

### 📸 Screenshots

![image](https://github.com/gitify-app/gitify/assets/1165961/28a03384-07ca-4c83-9baa-18d05281f6ce)

**Comment by setchy** [comment]
@pedro-mass - not until we implement #1124

Until then, I would suggest:

- disabling the `Detailed notifications` setting
- reducing the amount of unread notifications in your inbox
- ensuring this token is only used on one device
