### ISSUE TITLE
Hide notifications from bot accounts not working on native notifications

### ISSUE THREAD

**Issue by Araxeus** [gitify-app/gitify#1331]
I still get native notifications about PR's made by depandabot, when i open gitify they are not shown

### Gitify Version

5.9.0

### Operating System

Windows

### GitHub Account

GitHub Cloud

NOTES:

seems to happen because notifications arent filtered before being triggered natively

https://github.com/gitify-app/gitify/blob/b7157332f64a23c8d6a9447779c055213b37e08b/src/hooks/useNotifications.ts#L65-L81

**Comment by setchy** [comment]
https://github.com/gitify-app/gitify/blob/main/src%2Futils%2Fnotifications.ts#L123-L151

It should be filtering them 🤔

**Comment by Araxeus** [comment]
![image](https://github.com/gitify-app/gitify/assets/78568641/3f7b39a9-7950-4707-8638-1a53d0ae3787)

I don't know how it happened then 🤨

**Comment by setchy** [comment]
I haven't been able to recreate this, so I'll be closing this issue.

https://github.com/gitify-app/gitify/assets/386277/ba19dae4-3427-4a62-af30-7ec274dcfa6e

Note: once a native notification has been raised, we do not manage their state (clear, filter, etc)

**Comment by Araxeus** [comment]
Yeah I tried reproducing but I haven't been able either... Its so weird because i did get this notification this morning. 

ill throw it off as a cosmic ray 🤷‍♂️

**Comment by Araxeus** [comment]
@setchy @afonsojramos where did this option go? I just updated to v5.10.0 and its gone?

**Comment by afonsojramos** [comment]
@Araxeus I assume you found it 👀

**Comment by Araxeus** [comment]
haha yeah nothing to see here
