### ISSUE TITLE
Check for new versions of Gitify

### ISSUE THREAD

**Issue by bquorning** [gitify-app/gitify#1395]
### 📝 Provide a description of the new feature

I am always a couple of months behind the latest version, because I forget to check for updates to Gitify. Are there any plans for adding an automatic “check for new releases” feature?

**Comment by setchy** [comment]
We do already use [electron-updater](https://www.npmjs.com/package/electron-updater) to perform [automated update checks](https://github.com/gitify-app/gitify/blob/f513aa3441a8f4af84beababb3dff3d6f40ff930/src/electron/main.js#L64)

**Comment by bquorning** [comment]
I am using macOS Sonoma 14.5.

If the check only happens when Gitify is started (seeing `app.whenReady().then` and `on('ready'` in the code) then maybe it’s because I don’t restart my computer (or Gitify) very often.

Of course, it could also just be that I’m haven’t noticed the notifications 😅

Before manually updating Gitify next time, I’ll make sure to quit and restart it to see if I get a notification – and if not, I’ll reopen this issue.
