### ISSUE TITLE
review use of emojis for cross-platform compatability

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1446]
_Originally posted by @Araxeus in https://github.com/gitify-app/gitify/issues/1441#issuecomment-2273613028_

> 
> Same but the network error icon isnt even rendering for me (Windows)
> 
> ![image](https://github.com/user-attachments/assets/621918d1-ef4a-4b38-8757-8f1b0586ce02)
> 

This issue is to review all of our emojis to ensure they exist on macOS, Windows and Linux

**Comment by Araxeus** [comment]
here are all the emojis that arent supported on my windows machine:

![image](https://github.com/user-attachments/assets/6cceb959-914b-43d1-9575-d1f54fec6af5)

**Comment by setchy** [comment]
and on macOS
<img width="1027" alt="Screenshot 2024-08-07 at 11 23 03 AM" src="https://github.com/user-attachments/assets/fe7aa3f6-2bfc-4443-8198-674a09e29e4d">

**Comment by setchy** [comment]
@Araxeus - are you on Windows 11 or older?

TIL about https://emojipedia.org/wireless#designs

**Comment by Araxeus** [comment]
i'm on Windows 10 yes

**Comment by setchy** [comment]
> i'm on Windows 10 yes

Thanks! Looks like Windows 10 is using an Unicode/Emoji set from May 2019.

**Comment by Araxeus** [comment]
Windows 11 has under 30% adoption rate ([source](https://www.computerweekly.com/microscope/feature/Is-Windows-11-finally-ready-for-take-off#:~:text=Two%20years%20later%2C%20the%20latest,and%20Windows%2011%20on%2026.19%25.))

so we should probably support Windows 10 😅

**Comment by setchy** [comment]
@Araxeus - would you mind sharing a screenshot of the `ALL_READ_EMOJIS` for Windows

macOS
![Screenshot 2024-08-07 at 12 24 10 PM](https://github.com/user-attachments/assets/00907704-8a40-41ae-8ce1-c07aba6c3832)

**Comment by Araxeus** [comment]
![image](https://github.com/user-attachments/assets/c4701286-1929-481d-9af4-3317736b2efc)

**Comment by Araxeus** [comment]
I'd say replace them with whatever looks best?
