### ISSUE TITLE
Annoyance: Auto-update notifications

### ISSUE THREAD

**Issue by htunnicliff** [gitify-app/gitify#1447]
Gitify frequently triggers a notification whenever a new update is available. Is there a way to disable these or provide a mechanism for users to opt-out?

<img src="https://github.com/user-attachments/assets/aa74d7ef-ec75-43db-92cd-42e3c544dbf7" width="376px">

**Comment by setchy** [comment]
Are you referring to Native Notifications @htunnicliff?

**Comment by htunnicliff** [comment]
@setchy yes!

**Comment by setchy** [comment]
And to clarify, when you say "frequently triggers", are you getting multiple native notifications with the same content? If you can share a screenshot that would be appreciated

**Comment by htunnicliff** [comment]
As soon as one occurs, I'll be sure to add a screenshot.

The frequency has to do with the releases of Gitify. Every time there is a new release (e.g. every patch), a notification appears saying that the new release will be installed next time the app is restarted.

**Comment by setchy** [comment]
Ok, thanks for clarifying. 

It is true that our release cadence has increased throughout 2024. Hopefully most consider that a good thing after a few years of hibernation 😄.

**Comment by setchy** [comment]
Briefly looking at the [electron autoUpdater docs](https://www.electronjs.org/docs/latest/api/auto-updater), I cannot see any mention of an API to control the native notifications it raises upon `update-available` events

**Comment by setchy** [comment]
We can look to add a `System Setting` for users to configure if they want autoUpdates enabled.  Contributions also welcomed.

**Comment by htunnicliff** [comment]
I was able to add a screenshot to the issue description:

> <img src="https://github.com/user-attachments/assets/aa74d7ef-ec75-43db-92cd-42e3c544dbf7" width="376px">

**Comment by htunnicliff** [comment]
@setchy it appears this Electron guide gives an example for handling update events: [Updating Applications](https://www.electronjs.org/docs/latest/tutorial/updates#step-3-notifying-users-when-updates-are-available)

> Now that you've configured the basic update mechanism for your application, you need to ensure that the user will get notified when there's an update. This can be achieved using the [autoUpdater API events](https://www.electronjs.org/docs/latest/api/auto-updater#events):
> 
> ```js
> autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
>   const dialogOpts = {
>     type: 'info',
>     buttons: ['Restart', 'Later'],
>     title: 'Application Update',
>     message: process.platform === 'win32' ? releaseNotes : releaseName,
>     detail:
>       'A new version has been downloaded. Restart the application to apply the updates.'
>   }
> 
>   dialog.showMessageBox(dialogOpts).then((returnValue) => {
>     if (returnValue.response === 0) autoUpdater.quitAndInstall()
>   })
> })
> ```

**Comment by htunnicliff** [comment]
It looks like the relevant code in Gitify is here: 

https://github.com/gitify-app/gitify/blob/7c5d6b7d56e0fffa5d2a8a6ab9aaeda1cddbba4a/src/electron/main.js#L146-L166

**Comment by setchy** [comment]
Correct, that's the block. 

The native notifications (to the best of my knowledge) are automatic as part of the autoUpdater API for windows and macos platforms. 

The update events can be used for additional handling such as the tutorials demonstrated in-app dialog prompt.

**Comment by setchy** [comment]
A further clarification, in an "ideal scenario" would you still like to have automated updates but with the update native notification silenced, or, would you like to disable automated updates all together?

**Comment by htunnicliff** [comment]
Automatic updates are great! I'd personally prefer that they take place without a notification (which I believe is the case for most apps I have installed from both the web and from the Mac App Store).

**Comment by Araxeus** [comment]
Id like to add that disabling them should be optional and not default - I for one like those notifiations

**Comment by setchy** [comment]
In `v5.13.0` we switched our auto-update engine to [electron/update-electron-app](https://github.com/electron/update-electron-app), which takes care of a bunch of things, such as scheduled update checking and notifying users when a new version has been downloaded (restart now vs update later).  

For now, I'm going to close this ticket as unplanned.  We're happy to reconsider in future.
