### ISSUE TITLE
Arrow symbol in tray

### ISSUE THREAD

**Issue by florianmutter** [gitify-app/gitify#1448]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Gitify started to show an arrow in the tray. I could not find what this means and I also don't like applications taking up a lot of space in the tray.

### 🪜 Steps To Reproduce

Open Gitify 5.12.0

### Gitify Version

Other

### Operating System

macOS

### GitHub Account

GitHub Cloud

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/b0f82faa-cb9e-4f17-8f09-50166801ccce)

**Comment by setchy** [comment]
This is a recent engagement to indicate that a new version is available and has been downloaded. 

Upon restart it will launch 5.12.1 and the icon will be hidden

**Comment by florianmutter** [comment]
Is it this important to show to users that there is a new version? I actually don't care as long as it works :) I do want to have silent automatic updates. Maybe this can be made configurable

**Comment by setchy** [comment]
> Is it this important to show to users that there is a new version? 

We think so 😀

Really appreciate the feedback - I've proposed some updates on the linked PR
