### ISSUE TITLE
Login with OAuth App does not open even if everything is entered

### ISSUE THREAD

**Issue by shiron-dev** [gitify-app/gitify#1452]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I entered the Hostname, Client ID, and Client Secret in the "Login with OAuth App", but I cannot click the login button and the login screen does not open.

After examining the source code, I found that `authGitHub()` is called successfully, but when I execute `new BrowserWindow()`, it does not return any result and does not execute any code below it.

https://github.com/gitify-app/gitify/blob/7c5d6b7d56e0fffa5d2a8a6ab9aaeda1cddbba4a/src/utils/auth/utils.ts#L20-L30

For example, if the code is modified and executed as follows, `before new BrowserWindow()` is output, but `after new BrowserWindow()` is not.
```typescript
    console.log('before new BrowserWindow()');
    const authWindow = new BrowserWindow({
      width: 548,
      height: 736,
      show: true, }
    });
    console.log('after new BrowserWindow()');
```

### 🪜 Steps To Reproduce

1. Reset App (In my case, I have had this bug since the first time I installed it.)
2. Press the "Login with OAuth App" button
3. Fill in all contents
4. Press the Login button

Then nothing changes.The login screen does not open and no errors are output.

### Gitify Version

5.12.1

### Operating System

macOS

### GitHub Account

GitHub Cloud

**Comment by d-blackburn** [comment]
I can confirm this issue is happening on Windows too.

**Comment by setchy** [comment]
Thanks for reporting @shiron-dev and @d-blackburn.

Adding some logging this is the exception we're having

```
Failed to login with oauth app Error: @electron/remote is disabled for this WebContents. Call require("@electron/remote/main").enable(webContents) to enable it."
```
