### ISSUE TITLE
black tray icon is barely visible in gnome

### ISSUE THREAD

**Issue by mixtur** [gitify-app/gitify#1463]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

When there are active notifications the icon becomes green and its clearly visible, by when not - it is black and I can't even tell if the app is running or not.

Maybe make default icon white on dark themes. Or add white background or shadow below the icon.

### 🪜 Steps To Reproduce

Start the app on any recent Ubuntu with Gnome and dark theme.

### Gitify Version

5.12.1

### Operating System

Linux

### GitHub Account

GitHub Cloud

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/2fc5a7d0-d5a9-4ded-9c58-f5d7a5c45549)

**Comment by mixtur** [comment]
With new notification
![image](https://github.com/user-attachments/assets/03a4cb47-d688-45e8-90e5-a8451250127d)
Without notifications
![image](https://github.com/user-attachments/assets/5816c9e1-2bb2-43de-873b-c456cee54343)

**Comment by mixtur** [comment]
> Thank you for the quick response.

Thnk you for Gitify:) That is why I respond fast

**Comment by setchy** [comment]
Is it fair to assume that when using light theme on Ubuntu, everything is visible?

**Comment by mixtur** [comment]
Just tried it. The answer is no.

Many parts of the interface indeed become white on white theme, but not the top bar for some reason.

Maybe I am not representative.

I can only speak for what I see. I am on Ubuntu 24.04 LTS. There is also Gnome Tweaks installed on my system. It might mess with the theme.
Don't know what will happen on stock Ubuntu.

**Comment by mixtur** [comment]
Noted that the icon in main menu is very visible. Maybe some variation of that could work.
![image](https://github.com/user-attachments/assets/700922a9-82f1-4f41-a7fc-c50ffcf72a5b)

**Comment by setchy** [comment]
Over the weekend I setup a Ubuntu Desktop VM and was able to reproduce

![Screenshot 2024-08-19 at 10 07 02 PM](https://github.com/user-attachments/assets/fc096e23-783b-4a56-a63e-3668c034c65e)
