### ISSUE TITLE
"Unsubscribe from thread" button doesn't unsubscribe

### ISSUE THREAD

**Issue by y-nk** [gitify-app/gitify#1485]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I've used the bell icon (unsubscribe from thread) to silence notifications of some PRs, but going to the github notification panel i can see that those PRs are still subscribed to notifications. i wonder if it's expected behavior or bug ; if the PAT can't do this, there should be some log somewhere to reflect the failure imho.

### 🪜 Steps To Reproduce

1. click the bell icon next to a PR
2. click the bell icon under the Gitify logo to go to the Github notification panel
3. witness that the PR you silenced is still subscribed for notifications

### Gitify Version

5.13.1

### Operating System

macOS

### GitHub Account

GitHub Cloud

**Comment by setchy** [comment]
Thanks for reporting @y-nk - is there any errors you can share from the console logs or system logs?

**Comment by y-nk** [comment]
@setchy i did not inspect anything but i can have a look. where would logs show (on macOS)?

**Comment by y-nk** [comment]
i just checked the faq, found the network panel. the call fires well with a { ignored: true } payload

in gitify, click on the bell somewhere:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/dfcb61a6-d32e-471d-aebc-c964b29a8e12">

payload:
<img width="513" alt="image" src="https://github.com/user-attachments/assets/94257162-a246-4c3b-bb89-e39832539671">

response:
<img width="362" alt="image" src="https://github.com/user-attachments/assets/16b7d2c3-c7c2-486e-b4d3-66c8546a8beb">

that said, when clicking on the github notification panel, PR still shows in the list
<img width="495" alt="image" src="https://github.com/user-attachments/assets/3710e7b0-32f6-487c-8995-d712569475d9">

and only disappear after selecting the PR in the list + clicking the "unsubscribe" button

**Comment by setchy** [comment]
@y-nk - I spent some time this morning trying to reproduce the above issue, but unfortunately could not.  

I'm using v5.13.1 with GitHub Cloud.  I was able to repeatedly unsubscribe from notifications via the Gitify interface (mixture of issues and discussions) and see the corresponding changes in the GitHub UI (both on the specific items page, and the notifications inbox).

**Comment by y-nk** [comment]
@setchy thanks for spending the time in testing. i will look further again, reinstall and make sure all is well. i'm also using GitHub Cloud. I will close this as, since you can't reproduce, it's most likely that the problem is on my side.

**Comment by setchy** [comment]
No worries - always happy to reopen this ticket if you are still having issues and we can continue to triage 🕵️

**Comment by y-nk** [comment]
@setchy i think if i had to reopen it'd be to ask for a feature which a button which does the 3 calls (mark as read, unsubscribe and silence) in one click 😬

**Comment by setchy** [comment]
> @setchy i think if i had to reopen it'd be to ask for a feature which is a button doing the 3 calls (mark as read, unsubscribe and silence) in one click 😬

Maybe I'm missing something, but isn't this what happens today when you click the `Unsubscribe from Thread` notification icon in Gitify 🤔

**Comment by y-nk** [comment]
@setchy my bad for bad english: clicking the bell (unsubscribe) doesn't "mark as done" in a batch (but i worked the habit of 2 clicks)
