### ISSUE TITLE
Arrow down pictogram next to G icon in tray

### ISSUE THREAD

**Issue by iamart** [gitify-app/gitify#1489]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

What is this icon that won't go away?
If I had to guess - it's a new version available even though nothing would suggest that. On github I can see a newer version is available; though in the app settings there's a green mark suggesting latest version is installed (5.12.1; not 5.13.1 as in gh releases).
It's a bit annoying with absolutely no info.

### 🪜 Steps To Reproduce

look at the tray.

### Gitify Version

5.12.1

### Operating System

macOS

### GitHub Account

GitHub Cloud

### 📸 Screenshots

<img width="75" alt="Screenshot 2024-08-24 at 11 03 37 PM" src="https://github.com/user-attachments/assets/b7dc0350-1d12-42a1-b24c-8a5f98025230">

**Comment by setchy** [comment]
Please update to 5.13.1 which fixes this bug
