### ISSUE TITLE
Add support for fine-grained personal access token auth

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1492]
### 📝 Provide a description of the new feature

Currently we support the GitHub personal access tokens (classic)

This ticket is to enhance Gitify to also support [fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#fine-grained-personal-access-tokens) which are still in beta

**Comment by setchy** [comment]
From GitHub Support when clarifying misleading documentation of https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#list-notifications-for-the-authenticated-user%5D

> Thank you for reaching out to GitHub Support!
>  
> That section of the documentation is incorrect -- thank you for bringing this to our attention. At the moment, all notification API endpoints only support authentication using personal access token classic: https://docs.github.com/en/rest/activity/notifications?apiVersion=2022-11-28#about-github-notifications
>  
> 
>     These endpoints only support authentication using a personal access token (classic). For more information, see "[Managing your personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)."
> 
>  
> GitHub Apps and Fine-grained token isn't currently supported. I can see why this is misleading, I'd reach out to the relevant teams to have this docs updated to avoid confusion. The PM also mentioned this [here](https://github.com/orgs/community/discussions/36441#discussion-4480575) about FPAT not currently supporting Notifications API.
>  
> Please let me know if there is anything else I can assist with.
>  
> Best,
>  
> GitHub Support

Documentation has since been updated

**Comment by bmulholland** [comment]
At least they acknowledged it and quickly fixed the docs! Sucks it wasted your time though.

**Comment by setchy** [comment]
Added to https://github.com/gitify-app/gitify/issues/890

**Comment by setchy** [comment]
Looks like it may be on the 2025 GitHub roadmap: https://github.com/github/roadmap/issues/600
