### ISSUE TITLE
Open a browser with a new tab, not window

### ISSUE THREAD

**Issue by daeho-ro** [gitify-app/gitify#1532]
### 📝 Provide a description of the new feature

When I click the buttons like notification, issue and PR, it opens new browser window.
I really wish to open it as a new tab with existing browser window.

I uses an Arc browser, but it could be same as Chrome.

**Comment by setchy** [comment]
@daeho-ro - thanks for raising.  

This is interesting... for me new windows open in new tabs (not new windows).  

I suspect this might be solved through local device configuration / settings

**Comment by daeho-ro** [comment]
@setchy Indeed, it is only happen on Arc browser not Chrome.
