### ISSUE TITLE
When I click on the notification, it is marked as read, but it doesn't open the GitHub PR like it used to

### ISSUE THREAD

**Issue by mrodriguez90** [gitify-app/gitify#1550]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

When I click on the notification, it is marked as read, but it doesn't open the GitHub PR like it used to.
Maybe this isn't an issue, and it's a new setting I need to enable after the last version release?

### 🪜 Steps To Reproduce

1. Open Gitify desktop
2. Click on a PR notification

### Gitify Version

5.14.0

### Operating System

macOS

### GitHub Account

Combination

**Comment by setchy** [comment]
@mrodriguez90 - does it open the notification at all?

**Comment by mrodriguez90** [comment]
> @mrodriguez90 - does it open the notification at all?

@setchy nope:

https://github.com/user-attachments/assets/96ec4a8e-0b80-4002-bb20-d3ea05368e65

**Comment by setchy** [comment]
Interesting, thanks for the recording. 

Is there anything noteworthy in the console log or app logs (see: https://www.gitify.io/faq/)?

**Comment by mrodriguez90** [comment]
> Interesting, thanks for the recording.
> 
> Is there anything noteworthy in the console log or app logs (see: https://www.gitify.io/faq/)?

@setchy yes, I found this:

```
[2024-09-25 12:57:49.459] [error] Error occurred while fetching notification html url AxiosError: Request failed with status code 404
    at xr (file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:17247)
    at XMLHttpRequest.A (file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:21926)
    at ra.request (file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:30099)
    at async ii (file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:47773)
    at async file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:65736
    at async _o (file:///Applications/Gitify.app/Contents/Resources/app.asar/build/js/app.js:60:65634)
```

**Comment by mrodriguez90** [comment]
@setchy I solved this by signing out and then signing back in (I should have tried that earlier; my bad). It seems something happened with the repository permissions after updating Gitify. 
Thanks for your help!

Side note: It was confusing that I could see notifications for all the repos, but the URL/redirect didn't work.

**Comment by setchy** [comment]
Glad to hear that you found a fix.

I'll also look to update this logic to have a "worst case" fallback for future
