### ISSUE TITLE
Gitify displays the same notification repeatedly when using GHE Server

### ISSUE THREAD

**Issue by pddg** [gitify-app/gitify#1611]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I can't write the details because this problem only occurs in notifications from private GHE server. Sorry.

### Problem

In my environment, notifications that I have already “Marked as read” are displayed every time I refresh Gitify, and other new notifications are not loaded.

### Debugging

When I checked by starting up the Developer Tool, I found that a status code of 205 was being returned for the “Mark as read” process, and `/api/v3/notifications` returned 200. I found that it had already been marked as read in the GHE Server.

I refreshed the Gitify, then this notification appeared again on Gitify. This was the same even if I refreshed the page after marking the notification as read multiple times. Also, in this state, Gitify does not load new notifications from the GHE Server.

However, if I enable “Disable cache” from the Developer Tools, everything will work fine. Gitify will display new notifications and will no longer display notifications that have already been read.If I turn off “Disable cache”, it will return to its original state.

What I found interesting was that when Disable cache was turned off, it looked like no requests were actually being sent when refreshing notifications manually.
Developer Tool shows the message as follows:

![スクリーンショット 2024-10-29 14 30 29](https://github.com/user-attachments/assets/6a2ee88e-6b04-4068-ac0a-6be683ae3d24)
When I hover over the mouse cursor, the overlay will display as follows.

> Only provisional headers are available because the request was not sent over the network and instead was served from a local cache, which doesn't store the original request headers. Disable cache to see full request headers.

It seems that Gitify's requests to the GHE Server may include an `If-Modified-Since` header. When I made a request with this header using the `gh api` command, I got the following result. 

```
$ gh api --hostname xxx.xxx.xxx \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  -H 'If-Modified-Since: Tue, 29 Oct 2024 04:57:09 GMT' \
  '/notifications?participating=false'

gh: HTTP 304

$ gh api --hostname xxx.xxx.xxx \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  '/notifications?participating=false'

[]
```

### 🪜 Steps To Reproduce

Use GHE Server.

1. Press "Mark as read" for new notifications
2. Press "Refresh notifications"

### Gitify Version

5.16.1

### Operating System

macOS

### GitHub Account

Combination

**Comment by bmulholland** [comment]
What version of GHE is the server on?

**Comment by pddg** [comment]
Probably using 3.12.10.

**Comment by setchy** [comment]
I have a theory...

@pddg - can you confirm if you have any of these `Mark as Done` options enabled
![Screenshot 2024-10-29 at 6 32 29 AM](https://github.com/user-attachments/assets/06713f67-73bb-467f-a869-b3545ddbb536)

Mark as done is only supported on GitHub Enterprise 3.13.x or newer.  We have logic that hides the primary "mark as done" notification button, but I'm now thinking we need these guards around the other places it's used on (mark as read and mark as unsubscribe) interactions.

If you try disabling the settings you hopefully will have better luck 🤞

**Comment by pddg** [comment]
I will try it tomorrow ! Thank you!

**Comment by pddg** [comment]
`Mark as done on unsbuscribe` was only enabled in my environment.
The problem seems to exist after disabling these configs.

My current configuration about notification is as follows:
![スクリーンショット 2024-10-30 14 17 30](https://github.com/user-attachments/assets/89cc30da-4412-4c52-bfcc-4018cf184ff8)

**Comment by setchy** [comment]
Interesting, thanks @pddg.

Would you mind checking the API calls within Gitify that "Mark as Read", and try recreating these outside using curl or postman etc... 

They'll be  in the form `PATCH` https://{host}/notifications/threads/{id}

**Comment by pddg** [comment]
When I `Mark as read` from Gitify, the response was as follows:

![スクリーンショット 2024-10-31 8 19 18](https://github.com/user-attachments/assets/b556c6bd-c1ea-4307-a3d2-189c99fed23b)

205 is the status code returned when the process was successful, and the notification was actually marked as read.
https://docs.github.com/ja/rest/activity/notifications#mark-a-thread-as-read

Immediately after that, Gitify's automatic refresh was activated and I again received the notification I had just `Mark as read`……

I couldn't find a way to mark it as unread via the API, so I returned it to unread via the web UI, and then used curl to perform the same operation, but the result was the same.

```
THREAD_ID=
GHE_HOST=<my GHE server>
curl -L \
  -v \
  -X PATCH \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer $(gh auth token --hostname ${GHE_HOST})" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://${GHE_HOST}/api/v3/notifications/threads/${THREAD_ID}
```

```
* Request completely sent off
< HTTP/2 205
< server: GitHub.com
< date: Wed, 30 Oct 2024 23:35:50 GMT
< content-type: text/plain;charset=utf-8
< content-length: 0
```

Even after `Mark as read` from curl, it was still displayed as-is in Gitify.

At this time, there were several other unread notifications on the GHE Server, but these were not displayed in Gitify.

**Comment by setchy** [comment]
Thank you!

I'm now wondering if this line is problematic with GHE
https://github.com/gitify-app/gitify/blob/main/src%2Frenderer%2Futils%2Fapi%2Frequest.ts#L49

It would be interesting if changing this to always `no-cache` and testing locally helps. If it does, perhaps this needs to be behind a user settings, or influenced by GHE version.

**Comment by pddg** [comment]
I changed the suggested lines as follows:

```diff
diff --git a/src/renderer/utils/api/request.ts b/src/renderer/utils/api/request.ts
index f469cdfc..d9c09b09 100644
--- a/src/renderer/utils/api/request.ts
+++ b/src/renderer/utils/api/request.ts
@@ -46,9 +46,7 @@ export async function apiRequestAuth(
   axios.defaults.headers.common.Accept = 'application/json';
   axios.defaults.headers.common.Authorization = `token ${token}`;
   axios.defaults.headers.common['Content-Type'] = 'application/json';
-  axios.defaults.headers.common['Cache-Control'] = shouldRequestWithNoCache(url)
-    ? 'no-cache'
-    : '';
+  axios.defaults.headers.common['Cache-Control'] = 'no-cache';

   if (!fetchAllRecords) {
     return axios({ method, url, data });
```

Then, run the Gitify locally.

```
pnpm install
pnpm build
pnpm start
```

And do following:

1. Press "Mark as read" for new notification
2. Press "Refresh notifications"

The notification is shown again……
Warning message of `Probisional headers are show` is shown in Developer Tool for the request to fetch notification from GHE Server.

**Comment by setchy** [comment]
Hmm, thanks for testing @pddg. Without having access to a GHE environment I'm running out of suggestions. 

Hopefully you can continue triaging locally to find a resolution which we can apply and release

**Comment by pddg** [comment]
@setchy 
Maybe my previous attempt wasn't done properly. When I tried again today, it seemed that `Cache-Control: no-cache` solved the problem. 

I've created a PR ( #1622 ), so I'd be happy if you could review it.

**Comment by pddg** [comment]
v5.16.2 seems to work perfectly in my environment!
Thank you for your support!
