### ISSUE TITLE
Discussion comment notification does not point to the comment.

### ISSUE THREAD

**Issue by wkjung** [gitify-app/gitify#1645]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

If I click a gift notification by other commenter's reply in a discussion, it doesn't directly go to the comment.
Instead it redirects me to Discussion tab page (i.e. `https://<ghes-url>/<org>/<repo>/discussions`).
Which means I manually have to find out what exact discussion has a comment that notified me.

I found out that that it is because `#discussioncomment-<sum-number>` is missing in the gitify notification.
When I click a notification in **Github (GHES)'s Notification page**, the link url is like

```
https://<ghes-url>/<org>/<repo>/discussions/15?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE5NDQzNzEwOjk2OTAw#discussioncomment-13072
```
which redirects me to the correct comment.

BUT the same notification in **gitify** is missing the said `#discussioncomment`:

```
https://<ghes-url>/<org>/<repo>/discussions/15?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE5NDQzNzEwOjk2OTAw
```

btw our corporate is using GitHub Enterprise Server 3.11.15.

### 🪜 Steps To Reproduce

(in GHES)
1. Make another person to reply to any discussion that I am in the thread. Get 'commented' notification.
2. Gitify notifies me, so click the notification.
3. It drops me off at `<org>/<repo>/<discussion>` page, not to the specific discussion's comment.

### Gitify Version

5.16.2

### Operating System

macOS

### GitHub Account

GitHub Cloud

**Comment by setchy** [comment]
And what do you see in the application logs?

**Comment by setchy** [comment]
Thanks, this is helpful. 

I would suggest next steps be running the app from source locally and debug why the GraphQL query response fails

**Comment by setchy** [comment]
@wkjung - you have a few options.

You can follow the debug faq instructions located here: https://gitify.io/faq/ - within the network tab of the embedded browser you'll be able to inspect the graphql requests.

Alternatively, you could run [Gitify from source](https://github.com/gitify-app/gitify/blob/main/CONTRIBUTING.md#development) and debug https://github.com/gitify-app/gitify/blob/a34087bbace8c4b0e8a9a4f758c8e48ecad40d7a/src/renderer/utils/helpers.ts#L102-L119

**Comment by setchy** [comment]
Thanks @wkjung - this is helpful.  If you have a few moments could you kindly test this fix with your environment - https://github.com/gitify-app/gitify/pull/1665

**Comment by JakobEdding** [comment]
I have a similar issue where I click the Gitify notification for a reply to a PR review and the URL fragment `#discussion_r01234567890` is missing from the opened link. Does anyone have an idea what could be the problem? 

I checked the Gitify logs but there are no errors. The repos that his occurs for are from a github.com organization on the Team plan if this helps.

**Comment by JakobEdding** [comment]
Yes, I have that enabled. I saw that there is a hint about many unread notifications next to that setting. I assume it shouldn't be an issue to have ~120 notifications of which ~15 are unread?

**Comment by setchy** [comment]
The amount of notifications you have wouldn't be an issue.

If you have the interest, running the app from source locally is quite straight forward and will allow you to pinpoint where in https://github.com/gitify-app/gitify/blob/a34087bbace8c4b0e8a9a4f758c8e48ecad40d7a/src/renderer/utils/helpers.ts#L102-L119 it's failing for your notifications

**Comment by JakobEdding** [comment]
Thanks for the pointer. I ran it locally and observed that it goes into this block because `notification.subject.latest_comment_url` is `null`: https://github.com/gitify-app/gitify/blob/f21720cb59a668057bf941e0d4a5eebf726a9446/src/renderer/utils/helpers.ts#L128

I'm wondering whether this behavior is unexpected for Gitify now or whether there the GH API just doesn't reveal the `#discussion_r01234567890` fragment for this specific type of notification that I described above:
> notification for a reply to a PR review

**Comment by setchy** [comment]
Hmmm, that's unusual since for Discussions we have 

https://github.com/gitify-app/gitify/blob/f21720cb59a668057bf941e0d4a5eebf726a9446/src%2Frenderer%2Futils%2Fhelpers.ts#L113-L119

Which should force the Discussions lookup via GraphQL search 
https://github.com/gitify-app/gitify/blob/f21720cb59a668057bf941e0d4a5eebf726a9446/src%2Frenderer%2Futils%2Fhelpers.ts#L139

**Comment by JakobEdding** [comment]
In the case of these PR discussion comments, it is `notification.subject.type === 'PullRequest'` though so this branch is not reached.

**Comment by setchy** [comment]
> In the case of these PR discussion comments, it is `notification.subject.type === 'PullRequest'` though so this branch is not reached.

Ah, my misunderstanding - I hadn't picked up that you were talking about PR replies... this issue has been about GitHub Discussion notifications. 

I guess GitHub doesn't return a latest_comment_url for PR review replies 🤔
