### ISSUE TITLE
Linux build is not working

### ISSUE THREAD

**Issue by danielgomezriconeon** [gitify-app/gitify#1655]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I can start it but I never get notifications or repository list, it is always "empty":
![image](https://github.com/user-attachments/assets/a5975211-8060-48ce-91f6-78e7a2d6b57b)

I see the logs:
```console
[14518:1204/132855.489263:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

### 🪜 Steps To Reproduce

Install on Ubuntu 2410

### Gitify Version

v5.16.2

### Operating System

Linux

### GitHub Account

GitHub Cloud

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/a5975211-8060-48ce-91f6-78e7a2d6b57b)

**Comment by setchy** [comment]
@danielgomezriconeon any insights from the API requests (network tab or application logs)?

**Comment by setchy** [comment]
Woohoo, great news @danielgomezriconeon 🚀
