### ISSUE TITLE
dark theme scrollbar inconsistent

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#1666]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

The scrollbar should be dark when dark-theme is enabled.  On the main notifications screen it is showing as light, but when navigating to Settings or Filters it is dark.

### 🪜 Steps To Reproduce

1. Have enough notifications in inbox to cause scrolling
2. Enable dark theme
3. Observe difference between Home, Filter and Settings scrollbars

### Gitify Version

5.16.2

### Operating System

macOS

### GitHub Account

GitHub Cloud

### 📸 Screenshots

![2024-12-06T13-00-14 924Z-gitify-screenshot](https://github.com/user-attachments/assets/fdc6c7bf-ade6-41d9-8b77-a239c9d4974a)
![2024-12-06T13-00-19 107Z-gitify-screenshot](https://github.com/user-attachments/assets/03dfe44c-0238-452f-b029-d572446c170b)
![2024-12-06T13-00-22 412Z-gitify-screenshot](https://github.com/user-attachments/assets/c81019b2-5062-402a-a867-2150136b39e8)

**Comment by bmulholland** [comment]
FWIW this is a super common bug, I've seen it in apps like Notion

**Comment by setchy** [comment]
I haven't spent time triaging, but it's unusual the main screen behaves differently 🫠

**Comment by setchy** [comment]
Would you believe it... I can no longer reproduce it 🫠
