### ISSUE TITLE
links to issues lose the anchor portion of the href

### ISSUE THREAD

**Issue by alxndr** [gitify-app/gitify#173]
If I visit my notifications page and see that I have a notification linking to a specific comment on a PR, it will have a url like `https://github.com/owner/repo/pull/123#issuecomment-456`, with `#issuecomment-456` being the anchor pointing to the specific comment. However, clicking on this notification in Gitify will open a browser tab to `https://github.com/owner/repo/pull/123`, missing the anchor pointing to the comment.

**Comment by ekonstantinidis** [comment]
That would be great but it is not possible with the current Github API. Currently to achieve that we will have to make another request for each notification (if there are 50 notifications - that means 50 more requests). The reason this doesn't work one is [here](https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/notification.js#L19-L23). I've just sent an email to GitHub regarding adding an `html_url` field for the `subject` of each notification. Fingers crossed!

**Comment by frapontillo** [comment]
Are there any updates about this? This is really a deal breaker 😢 . Could we alternatively get the workaround through that additional API call?

**Comment by frapontillo** [comment]
So maybe since Github now has the [GraphQL API](http://githubengineering.com/the-github-graphql-api/) we might be able to add the URL to the request?

More info at: https://developer.github.com/early-access/graphql/

**Comment by lgeiger** [comment]
@manosim As a workaround we could use [`latest_comment_url`](https://developer.github.com/v3/activity/notifications/#list-your-notifications) instead of `url`. For most cases this would be the correct URL.

**Comment by manosim** [comment]
@lgeiger That would make sense but unfortunately it's still a url to the api (not an `html_url`) so have to check all types of notifications and see whether they are returning this field etc. Will investigate further - it is a nice idea!

@frapontillo That is exactly what we need - I had a look on the GraphQL API and it looks promising but it is currently missing `notifications`. Was informed that they GitHub team is planning to include notifications at some point so fingers crossed!

**Comment by lgeiger** [comment]
Thanks for your work!
