### ISSUE TITLE
Different colour icons

### ISSUE THREAD

**Issue by RealOrangeOne** [gitify-app/gitify#197]
For people that use platforms with dark coloured notification bars, we need an option to switch the colour of the idle tray icon to something lighter, so its actually visible.

**Comment by ekonstantinidis** [comment]
We could possible do that only for **linux** (not sure about **windows**) since OSX's dark theme can handle tray icons.

**Comment by Komposten** [comment]
+1 for this.

Doesn't necessarily have to auto-detect the theme (although that is doable, at least on Windows and MacOS). I'd be happy with a simple option in Gitify's setting page to "Use bright icon" or something like that.

**Comment by hyrious** [comment]
It's 2020. Now we should have ability to resolve this issue:
- [nativeTheme.shouldUseDarkColors](https://www.electronjs.org/docs/api/native-theme)

**Comment by setchy** [comment]
Closing this issue as there is code now that will handle `nativeTheme.shouldUseDarkColors`.  

Please re-open if this issue still requires attention.
