### ISSUE TITLE
Open links in Background

### ISSUE THREAD

**Issue by stefanjudis** [gitify-app/gitify#200]
Hey hey - thanks for this great project. I'm really enjoying it.

The only thing that I'd really like to have is the possibility to open links in the background.
My flow usually is to scan all notifications and then when done, look at all the newly opened tabs.

Right now gitify closes whenever I click something.

A settings option like "open in background" would be awesome. :)

I you agree on the usefulness, I'm also open to provide a PR for it.

**Comment by afonsojramos** [comment]
If you're still up for the challenge, 7 years later, we could still use this @stefanjudis :)
