### ISSUE TITLE
The new logo looks a lot like Google's one

### ISSUE THREAD

**Issue by laughedelic** [gitify-app/gitify#233]
It's not an issue, but I just think about it every time I look at it, so I decided to say it aloud 😅 

|  |  |
| :-- | :-: |
| gitify | ![](https://github.com/manosim/gitify/raw/master/images/tray-idleTemplate%402x.png) |
| google | ![new-google-favicon-logo](https://cloud.githubusercontent.com/assets/766656/18805277/03284ec2-8209-11e6-9b4b-79ff1cde35d3.png) |
| google+ | ![google-plus-new-icon-logo](https://cloud.githubusercontent.com/assets/766656/18805281/38194b54-8209-11e6-8e3c-42c647597486.png) |

I do see the difference, but it still looks very alike.

**Comment by F1LT3R** [comment]
Agreed.

Why not use the Github Octocat? Seems more relevant. Besides... the :octocat: is 😎!

**Comment by jpmckearin** [comment]
I don't typically +1, but when I do...

ahhh screw it. +1

**Comment by smileytechguy** [comment]
or maybe not the :octocat: if it will support other accounts such as bitbucket etc, maybe just the git branch icon?

**Comment by luangch** [comment]
Agreed.
