### ISSUE TITLE
Can't do anything when network not found

### ISSUE THREAD

**Issue by sedubois** [gitify-app/gitify#239]
Hi and thanks for this project 😊 
Regularly (every few days), the macOS client doesn't detect internet any more (although it is actually available). In that case the popup shows that it doesn't detect internet, but offers no way to access the settings and quit Gitify. I'm forced to kill the processes found with `ps -ef | grep Gitify`. (and after restart, it connects fine.)

Besides trying to figure out why it loses connectivity, I recommend making sure settings are avaliable even in case of error.

**Comment by janicmikes** [comment]
👍 A "regular" quit should be possible even without an active network connection.

**Comment by bmulholland** [comment]
It's been quite a while and we've released a new version now. Hopefully this is resolved -- but if it isn't, please let us know and we'll re-open.
