### ISSUE TITLE
Mark all notifications as read

### ISSUE THREAD

**Issue by chipironcin** [gitify-app/gitify#249]
Currently, it seems there is no way of marking *all* notifications as read.
You can mark as read all notifications within a repository but no all the notifications from all the repositories.

It would be awesome if someone could take a look at this and implement (should be easy as Github already has that feature, maybe it is an existing endpoint).

Cheers!
cc/ @carrodher

**Comment by carrodher** [comment]
+1 
<img width="1051" alt="screen shot 2016-12-23 at 12 02 37" src="https://cloud.githubusercontent.com/assets/13216600/21452558/06965aa4-c908-11e6-96ee-33bcfd6f1e0f.png">

**Comment by CHR15-** [comment]
+25

**Comment by AriLFrankel** [comment]
@manosim I am happy to take this on!
