### ISSUE TITLE
Linux version and release of mobile apps for Europe

### ISSUE THREAD

**Issue by michaljuris** [gitify-app/gitify#256]
Hi

are there any plans for Linux version and release of mobile apps for Europe?

Thanks

**Comment by m1guelpf** [comment]
@manosim Updates?

**Comment by manosim** [comment]
Hi there! Currently I am working on supporting Github Enterprise in Version 2. Very shortly after that I am planning to land support for Linux & Windows too (will be a lot easier with V2).

For iOS the app is currently on the app store ([read more](https://github.com/manosim/gitify/issues/261#issuecomment-285179041)). For Android I will re-upload it with the next version so fingers crossed (after Gitify supports GitHub Enterprise, Linux & Windows)!

That's pretty much the plan!

**Comment by pragmaticivan** [comment]
Hi there, any plans for that release still? thanks!
