### ISSUE TITLE
Allow for simple reason filtering

### ISSUE THREAD

**Issue by michenly** [gitify-app/gitify#264]
Using Github API's reason field
https://developer.github.com/v3/activity/notifications/
<img width="684" alt="screen shot 2017-02-15 at 4 43 02 pm" src="https://cloud.githubusercontent.com/assets/1610169/22996777/eb8a3c7e-f39d-11e6-93af-3a4325578bbe.png">

Do a quick filtering to only show certain type of notification. 
I am thinking a simple toggle of yes or no to included each type of reason.

ie. I can turn off all the notification except for the one specially @mentioned me

**Comment by icatalina** [comment]
It will be cool to have one of this per repo. There are some repos I want to be notified all the time, others where I only care if I'm mentioned....

**Comment by icatalina** [comment]
It will be cool to have one of this per repo. There are some repos I want to be notified all the time, others where I only care if I'm mentioned....

**Comment by nilsreichardt** [comment]
I have the same use case as @icatalina

**Comment by Juice805** [comment]
Isn't this an option in Github itself in the "Watch" Menu? Maybe not back in 2017, but today I think this is already possible.
<img width="359" alt="Screen Shot 2022-05-12 at 4 50 19 PM" src="https://user-images.githubusercontent.com/8647159/168185232-939a473e-f611-4587-beeb-2ff4d0f07706.png">

**Comment by nilsreichardt** [comment]
For me, this not a solution because I subscribed via this menu to many repos. I get ~100 notifications per day because I'm interested in the process of these repositories. But I don't want to get macOS notifications via Gitify for all the 100 GitHub notifications (this would be too crazy and I couldn’t work anymore). It would be nice if I could say that I only want for Repo X or when I'm a participant a Gitify macOS notification.

**Comment by kpurdon** [comment]
This would be a great addition -- github's notification filtering is poor at best, and being able to do even this thin filtering in gitify would be 💯 . 

My specific use case is disabling team mentions so I don't get every PR where the team is left around after auto-assignment to somebody else. There is a setting to disable that, but I don't have control of that.
