### ISSUE TITLE
iOS doesn't have push notifications

### ISSUE THREAD

**Issue by ArchdukeTim** [gitify-app/gitify#272]
t's the reason I paid 99¢, so I would suggest removing the price tag until the one thing that makes this app useful is implemented.

**Comment by OGKevin** [comment]
Is there any news on this? I also just payed €1,09 to find out that im not receiving any notifications at all 😠.

**Comment by OGKevin** [comment]
Is there any news on this !? 😡

**Comment by bmulholland** [comment]
Sorry folks, we're taking this over now and weren't involved back then. I'm not sure what happened with iOS but I have no context and I don't think iOS is supported anymore. Apologies that you paid and didn't get much support or push notifications.
