### ISSUE TITLE
persistent pop-up notifications

### ISSUE THREAD

**Issue by jaufgang** [gitify-app/gitify#281]
Currently, when I get a pull request, I hear a beep and see a pop-up notification that disappears after a few seconds.  If I am away from my desk when this occurs, I do not see that notification.  I recognize that the Gitify icon changes colours, but it is still not very eye catching.

It would be helpful to have to option to set the pop-up notifications to be persistent (i.e. remain on the screen until they are dismissed with a click)  Perhaps there could be settings to set which types of notification are persistent individually.

**Comment by bmulholland** [comment]
This is an OS-level notification feature. You should be able to configure your notifications to do this on your own. On macOS, that's setting the notification style to Alert. Not only do we not want to re-invent the wheel, but it's not even clear this is possible. Adding it as a non-goal of Gitify. https://github.com/gitify-app/gitify/issues/655
