### ISSUE TITLE
Highlight participating when displaying all notifications

### ISSUE THREAD

**Issue by nihonjinrxs** [gitify-app/gitify#307]
It would be nice, in the default case when you're not displaying only the notifications you're participating in, to highlight (or indicate some other way) those you are participating in.

In my case, I'd like to be able to see all my notifications, but easily handle the participating ones with more urgency than others.

If I have some time, I can dig in and see about adding this.

**Comment by setchy** [comment]
Unfortunately `https://api.github.com/notifications` response doesn't contain any indicator of participating or not...

We'd probably have to always make both calls, `/notifications?participating=true` and `/notifications?participating=false`, and then parse the responses to find the difference.

**Comment by setchy** [comment]
After further testing and observing how the `/notifications` API behaves, ALL participating notifications will have the `reason:mention`. 

Since we display the notification reason prominently already, I will go ahead and close this as not planned
