### ISSUE TITLE
[Enhancement] Add color coding

### ISSUE THREAD

**Issue by ArchdukeTim** [gitify-app/gitify#326]
When viewing notifications on github.com they will be color coded. It would be nice to see those with gitify. Sometimes I don't care if a PR is merged or an issue is closed, but I do like knowing about updates.

**Comment by jabbett** [comment]
This would be particularly powerful for the first-time-user scenario. I open Gitify and suddenly see 50 notifications, some recent, some months old. I could get through the list far faster if I could see if the underlying pull request or issue were merged/closed already. Thanks!

**Comment by rdohms** [comment]
Yeah my idea would be add at least a status icon of the underlying pr/issue.

**Comment by Komposten** [comment]
+1 to this!

Would be amazing if just a glance at a PR would let me know if it is a draft, open, closed or merged. That would make it a lot easier to determine how a PR was updated without having to click through to it.

**Comment by ArchdukeTim** [comment]
I've done some investigation on this. Github notifications don't provide any information about the state of the item being notified about, so an additional call would have to be made for each notification to get more info

**Comment by manosim** [comment]
That would be my favourite feature but as @ArchdukeTim mentioned we would need an extra request for each notification which is not ideal. Hopefully something we can add when GitHub releases support for notifications in the GraphQL API.

**Comment by abannach** [comment]
+1 to this request. I get a lot of notifications for merged requests and either seeing color coded that it's merged or an icon would be helpful.

**Comment by ArchdukeTim** [comment]
Papa bless 🙏🏼
