### ISSUE TITLE
about for linux

### ISSUE THREAD

**Issue by Suremotoo** [gitify-app/gitify#329]
how run or install gittify for linux ?

**Comment by orsonteodoro** [comment]
Working on Gentoo Linux as of 2/20/2019

Download and install Electron
Download Gitify release 2.0.2 (or whatever version you prefer)

cd into source

# patch software
sed -i -e "s|\"electron\": \"=1.6.10\",|\"electron\": \"^1.6.10\",|g" package.json || exit 1
sed -i -e "s|\"sass-lint\": \"=1.10.2 -v\",|\"sass-lint\": \"=1.10.2\",|g" package.json || exit 2
sed -i -e 's|path: process.execPath.match|//path: process.execPath.match|' main.js || exit 3

# download deps
npm install --production || exit 4

# check and replace vulnerable packages
npm i --package-lock || exit 5
npm audit fix --force || exit 6

npm install browserify || exit 7
npm install uglifyjs || exit 8

npm run build || exit 9

npm remove browserify || exit 10
npm remove uglifyjs || exit 11

npm prune --production

electron .
