### ISSUE TITLE
See past notifications?

### ISSUE THREAD

**Issue by nitrocode** [gitify-app/gitify#332]
Great app! I like getting notifications that much faster but... main reason I installed gitify was to see past notifications.  

Is it possible to see or save / keep past notifications? or to put it on the roadmap? 

I have a tendency to login to github, look at my notifications, and say "I'll get to this later", and I never do because the notification is missing so I've now been bookmarking specific issues I want to get back to...

I also bookmarked this issue. 🤣

**Comment by JakeSidSmith** [comment]
It looks like this should be possible from the documentation [here](https://developer.github.com/v3/activity/notifications/#list-your-notifications), but I'm not sure how this would fit into Gitify's current purpose and or UI.

Perhaps adding a link to [all notifications](https://github.com/notifications?all=1) would suffice?

**Comment by nitrocode** [comment]
Thanks for the comment. Unfortunately that link will only show recent notifications. There isn't an easy way in github to show past notifications.

**Comment by JakeSidSmith** [comment]
Oh, you mean like really old ones? o__O

**Comment by nitrocode** [comment]
Like ones that are older than a week. Kind of like how you can login to your email and once you read your email, it doesn't vanish after a week. It will still be there so you can click on it. Github seems to strictly enforce notification zero (like inbox zero) and one way around that would be to build the feature into an app like this one that parses the notifications.

**Comment by JakeSidSmith** [comment]
A "watch later" (like YouTube) kind of thing would be nice. I also end up with a million tabs on one browser window that just link to open issues.
