### ISSUE TITLE
Pushing commits to my own pull requests gives me a gitify notification

### ISSUE THREAD

**Issue by lCharlie123l** [gitify-app/gitify#334]
Pushing commits to my own pull requests gives me a gitify notification each time I push a new commit with the notification type "Author" - ill try to add a screenshot next time I see it.

Using version 2.0.2 on MacOS High Sierra 10.13.13

Im not sure if this has any relevance or not but Im using signed commits.

**Comment by JakeSidSmith** [comment]
@lCharlie123l I'm not sure there's any way to prevent this, as this presumably is just how the GitHub notifications are handled.

**Comment by twinters007** [comment]
I sign my commits, and don't get this. It most likely has to do with your github settings.

**Comment by lCharlie123l** [comment]
It looks like it it might be due to me pushing my commits using my work email account as the primary account locally for work projects when its not my primary github account leading to notifications on the main account. However - i dont get these notifications in github only on gitify (this could however be a red herring) but it seems to go away if I change my local email to be that of my github one.

**Comment by twinters007** [comment]
Interesting how it still labels you as author even though its from a different account
