### ISSUE TITLE
Feature Request: Start minimised to tray only

### ISSUE THREAD

**Issue by lCharlie123l** [gitify-app/gitify#335]
When the app opens at startup it opens the full application window. It would nice to have an option to start minimised in the tray (and probably the same again to start minimised to the dock for those who use it in that configuration).

**Comment by AriLFrankel** [comment]
I'd be happy to take this on in Desktop if it's a feature you'd be interested in having added @manosim !

**Comment by bmulholland** [comment]
I think it works this way now? Closing as stale. Let me know if I'm missing anything.

**Comment by ninjaeon** [comment]
I'm on Gitify v6.3.0 Windows 11 and using the open at startup option in settings.  The Gitify window displays at startup on it's own.
