### ISSUE TITLE
Let users know how to add Enterprise & Personal Accounts at same time

### ISSUE THREAD

**Issue by FrancesCoronel** [gitify-app/gitify#338]
I'm having trouble adding on my personal GitHub account after first adding my enterprise account. Is there an option through the app to make this happen?

Overall, very happy with it so thanks for the hard work! 👍

**Comment by docwhat** [comment]
I think the current design means you should add the public _first_ then add the enterprise.

**Comment by fvcproductions** [comment]
Going to update issue to reflect that you are able to do this - it's just not obvious or documented anywhere.

**Comment by setchy** [comment]
v5.6.0 includes extensive updates to auth. This should now be more intuitive.
