### ISSUE TITLE
Feature Request: Filter out notifications for closed PRs

### ISSUE THREAD

**Issue by maxcbc** [gitify-app/gitify#342]
I often get asked to be a reviewer on PRs which are then reviewed by others and merged. We tend to ask everyone in our team and review on a first come first serve. It'd be nice to autoclose notifications which have already been merged.

**Comment by michelleyschen** [comment]
Maybe there can be a button to "mark as read" for all close & merged issue instead?

**Comment by florrain** [comment]
+1

**Comment by BroderickCarlin** [comment]
+1
