### ISSUE TITLE
Feature request - close on escape key press

### ISSUE THREAD

**Issue by JakeSidSmith** [gitify-app/gitify#377]
Pretty self explanatory. I don't mind adding this, but thought I'd leave a note here. 😛

**Comment by JakeSidSmith** [comment]
Side note: might be nice to have a shortcut to open it also.

**Comment by jonesdhtx** [comment]
This would be nice! Also would be nice if there was a setting to auto-close after "ok"ing the last notification and you have the empty list and the fancy animation. It could be closing slowly while showing the animation or at least close after the animation.  Note: I have the setting "on click mark as read" turned on

**Comment by benwoodward** [comment]
Would appreciate this, I always hit escape to close the window forgetting the shortcut doesn't work.
