### ISSUE TITLE
Feature Request: Click through to PR when GitHub Actions run completes

### ISSUE THREAD

**Issue by CharlieHarle** [gitify-app/gitify#381]
When using GitHub actions CI Gitify will notify you when a run completes but you are unable to click through to that PR because it is 'Unknown'

<img width="499" alt="Image 2020-02-18 at 2 24 10 pm" src="https://user-images.githubusercontent.com/10830524/74744820-c7275780-525a-11ea-8096-9f4e4dee96d3.png">

**Comment by codebytere** [comment]
For some context - the issue here lies with the GitHub V3 API, which fails to return a url when the notification type is a ci workflow run. I've opened an issue with the GitHub folks behind the API on the notifications team, so when they fix this it should automatically work within the app.

**Comment by aehlke** [comment]
@codebytere any update? thanks

**Comment by florianmutter** [comment]
@codebytere is the issue you created public? Could you maybe add a link here?
