### ISSUE TITLE
Unable to authorize private repos after forgetting to do so during first log in.

### ISSUE THREAD

**Issue by joeletizia** [gitify-app/gitify#394]
When a user logs in for the first time, but forgets to get authorization for their private organization's repos, they have no opportunity to do so when logging in again. That step is skipped and they are fully logged in.

I imagine there is a way to clear this user data and go through the setup flow again, but I do not know how.

**Comment by giliamverheide** [comment]
+1 Would like to see this too. I think a workaround could be going to your [Authorized OAuth Apps](https://github.com/settings/applications), revoking accessing and going through the flow again (haven't tested yet).

**Comment by philippgeisler** [comment]
+1 just ran into exact this issue and hope this gets addressed in some way.

**Comment by bmulholland** [comment]
Isn't this part of the flow fully controlled by Github? I'm not sure there's anything we can do about it.

Github does allow you to change it, just go to the authorized oauth apps link above, find Gitify, and use the Github UI at the bottom.

Closing this as something Github does, and that we can't control. If anyone has a practical, feasible idea what we could do to make this better, happy to consider that. Let me know.
