### ISSUE TITLE
Which Authorization callback URL should be used when setting up a new OAuth app?

### ISSUE THREAD

**Issue by Stefanama** [gitify-app/gitify#395]

**Comment by ivandov** [comment]
Issue #327 seems to address this issue, but I would keep this issue open around new documentation necessary either in the Wiki or in the main README.md

Unfortunately there is no guidance around how to do this correctly from anywhere I can find.

**Comment by manosim** [comment]
Hi there, the callback for the app is set to `https://www.gitify.io/callback`. Used to be `http://localhost/callback` but had some issues when I upgraded electron. Unfortunately I don't have access to an enterprise account so I cannot test this properly.

PS. If anyone is willing to give me access to an enterprise instance (even with no access to repos etc.), that would be amazing!

**Comment by antoniojgage** [comment]
@manosim as of today I can confirm this works for enterprise ☝️

**Comment by manosim** [comment]
That's great - I'm planning to create a new page on the website with documentation around this and put a link in the Enterprise login page. Will leave this issue open until it's done.
