### ISSUE TITLE
Github Enterprise + Github accounts issues

### ISSUE THREAD

**Issue by fmunteanu** [gitify-app/gitify#409]
If I login first into Github, then into Enterprise, my Enterprise notifications do not show anymore. But if I login only into Enterprise, I can see the notifications. In other words, I cannot get notifications from both accounts, just one account at the time.

I don't know how often the check is done, but while logged with only Github account, 30min later I did not get a notification that I created this issue.

Once logged into Github with no notifications displayed, I'm adding Github Enterprise account where I have several issues. Once logged into Github Enterprise, I show no notifications. However, if I logout all accounts and only login only into Github Enterprise, I can see my notifications listed correctly.

If I add first my Github Enterprise account, I'm not able to add anymore a Github account. More exactly, in Settings, I should see `[Logout Enterprise] [Add Github]`, instead of `[Add Enterprise] [Logout]`.

<img width="500" alt="Screen Shot 2020-05-17 at 2 55 02 AM" src="https://user-images.githubusercontent.com/19806136/82137920-2ceb9700-97ea-11ea-90dd-b6d9171cf43c.png">

Even if I'm logged into both accounts, I can still see `[Add Enterprise]` button, it should not be present anymore. I would expect to see buttons like: `[Logout Enterprise] [Add Github] [Quit]`

Also, we should have a feature where we can see into what accounts we are logged. Github, Enterprise. For example, instead of showing `[Logout from all accounts]`, we should have a button for each account: `[Logout Enterprise] [Logout Github] [Quit]`.

<img width="500" alt="Screen Shot 2020-05-17 at 3 08 05 AM" src="https://user-images.githubusercontent.com/19806136/82138085-b2bc1200-97eb-11ea-8842-ffd73eba41e2.png">

**Comment by bmulholland** [comment]
Closing this as stale, please let me know if it's still an issue
