### ISSUE TITLE
Request: show notifications only for certain time periods

### ISSUE THREAD

**Issue by nitrocode** [gitify-app/gitify#416]
Great app! I use it all the time.

During work I get distracted easily by github noise and I'd like to set my personal account notifications to only show before 9 AM, from noon to 1 pm, and after 6 pm. It would be helpful. At the moment, I'm simply closing the app when I don't want to see notifications and have to remind myself to reopen it.

**Comment by bmulholland** [comment]
The notification settings of macOS (and maybe Windows?) supports this now. I don't think we should re-implement OS-level features, so closing this out.
