### ISSUE TITLE
Gitify does not send any notification from github.com if it is not able to access to GitHub Enterprise server.

### ISSUE THREAD

**Issue by pddg** [gitify-app/gitify#423]
## Environment

- macOS Catalina 10.15.5
- Gitify v3.0.5

## Expected behavior

Notification of github.com is appeared even if Gitify cannot reach GitHub Enterprise (GH:E) server (i.e. server downed, or disconnected from the networks of GH:E server...etc). 

## Actual behavior

In my environment, I use VPN to connect to GH:E server.  Gitify doesn't send any notifications from github.com during disabling the VPN. If the VPN is enabled (Gitify becomes to be able to connect to GH:E server), Gitify send the notifications from both of github.com and GH:E.

**Comment by lilyball** [comment]
It doesn't just not send notifications, but it also replaces the entire UI with a "Something went wrong" page so I can't even check the notifications myself.

**Comment by bmulholland** [comment]
Notifications and displaying the window both require information from the server. If it can't contact the server, it doesn't know what to display. Beyond that, none of the UI would work. We could perhaps improve caching and display that, but that's a lot of work for a very minor benefit in a niche scenario. I don't think it's worth the work.

**Comment by pddg** [comment]
Github.com and GH:E server are independent entities, and failures can occur at each.
Not being able to display both when one is inaccessible is not the behavior expected by users, I think.

However, I do not know how difficult it would be to change this behavior, so I respect the maintainer's decision.

**Comment by bmulholland** [comment]
Oh, I misread 😅

Yeah that makes more sense. I think the requests could be more resilient for errors.

**Comment by setchy** [comment]
I think `fetchNotifications` will need to be tweaked to support this. 

https://github.com/gitify-app/gitify/blob/f4053f529f92ba8740ee570be349001855cb1e66/src/hooks/useNotifications.ts#L64

@pddg - contributions welcomed 🙏

**Comment by afonsojramos** [comment]
This also happens in the case that a specific organisation requires SAML Authorisation.

<img width="1825" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/e2ca7d74-ad8c-4aa3-ad70-f78a9a33881c">
