### ISSUE TITLE
App tries to phone home after login

### ISSUE THREAD

**Issue by unikitty37** [gitify-app/gitify#429]
I use Little Snitch to monitor outbound connections on my Mac. When I run Gitify, and authorise it to connect to the various github.com hosts that it uses, it tries to connect to gitify.io after I complete login. If I deny this connection, the window stays completely blank.

I can't find any references to gitify.io in the code outside of the tests — what is Gitify trying to do here? I wouldn't have thought it would need to phone home except to check for an updated version, and that would usually happen on launch, rather than immediately after logging in…

**Comment by banderson** [comment]
Perhaps related to https://github.com/manosim/gitify/issues/395#issuecomment-608586025 ?
