### ISSUE TITLE
Can't add github.com account after I've configured Enterprise

### ISSUE THREAD

**Issue by lilyball** [gitify-app/gitify#430]
I configured Gitify for GHE and skipped github.com during initial setup. Looking at it now, there's no way to add the github.com support; the Settings page just has an "Add Enterprise" button that, when clicked, takes me back to the already-configured enterprise (which I suppose means there's no way to add multiple GHE installations either).

**Comment by lilyball** [comment]
I went ahead and logged out of GHE, then logged in to github.com, and then back into GHE. Very annoying, but it mostly worked. I actually had to then quit and relaunch Gitify before it showed the GHE notifications for some reason.

**Comment by nirvanarsc** [comment]
Noticed this issue today 😅

**Comment by Juice805** [comment]
The workaround doesn't work either as I can't use the Personal Access Token method to login to enterprise if I log into github.com first.

**Comment by yyar** [comment]
@Juice805 I think that this PR already merged (#524) will help login to enterprise Github using PAT, but it doesn't release yet.
