### ISSUE TITLE
Multiple instances for different accounts

### ISSUE THREAD

**Issue by lilyball** [gitify-app/gitify#431]
Right now if I log into both github.com and GHE, Gitify uses a single status bar item (macOS) that shows notifications for both in a single window.

I'd really like to be able to get a separate status bar item per account, ideally with customization of the colors (so I can quickly distinguish them at a glance) or perhaps varying image options. This way I can tell just by glancing at my status bar whether I have notifications for github.com or for GHE and I can deal with them separately.

Ideally this would be a single app that has multiple status items, which suggests the preferences would need to go into their own window instead of replacing the current window contents. Less ideally, if there was a simple way of making multiple Gitify instances on disk with unique identifiers (so their persisted settings don't conflict) such that I can run them separately.

**Comment by kinueng** [comment]
My workaround is to run two instances of Gitify.  The downside is the second instance of Gitify doesn't persist its login if the application instance is terminated.  I do not often restart Gitify or my MacBook, so my hope is this workaround is enough to get by.

1.  Launch Gitify with Spotlight Search (Command + Space)
2.  Log into GHE
3.  Open Terminal
4. Run `open -n /Applications/Gitify.app/`
5.  Log into GitHub with second Gitify instance

End result is two unique "G" icons.  One icon is Github, and the other icon is GHE.
![image](https://user-images.githubusercontent.com/31117513/103802212-6b052780-5014-11eb-8aa5-869efd110c34.png)

_Disclaimer: I've only used this workaround for a few hours, so far so good._

**Comment by parties** [comment]
You can also just duplicate the executable. Just copy and paste the application to create a "Gitify Copy.app", then rename if you wish (I named mine "Github Enterprise.app") and open/run it.

I haven't verified it yet but I anticipate this will solve the login issues that @kinueng is experiencing.

**Comment by kinueng** [comment]
Hello @parties, having a duplicate application still has the same limitation with the second Gitify instance requiring GitHub login every time.

I tried your suggestion to duplicate the `Gitify.app` directory. Now I have a macOS apps `Gitify.app` and `Gitify GHE.app`. 

What surprised me is observing the login credentials and information are shared by both applications. The first instance of Gitify is always pointing to the first GitHub login, regardless if the instance is launched with `Gitify.app` or `Gitify GHE.app`. Launching a second instance of Gitify always requires logging into the desired GitHub domain.

**Comment by setchy** [comment]
For this to move forward, we'll need to make changes to `storage.ts` to save accounts+settings per executable

**Comment by afonsojramos** [comment]
@setchy I'd argue that with multiple account support, this is something that we do not want to support 🤔

**Comment by setchy** [comment]
I've been thinking about the same thing while I was building the new account module.  

That certainly goes a long way towards multiple account support. 

These are the additional features I've been thinking that some users _may_ use depending on their workflow::

- separate instances per account (or grouping of accounts). eg: personal vs work.   I think this will require some changes to  our storage module, as well as possibly allowing each instance to be differentiated (ie: taskbar unread color)
- increase resilience if one of their accounts fails to fetch notifications (eg: work requires VPN) - solved by https://github.com/gitify-app/gitify/issues/423 or avoided by having separate Gitify instances

**Comment by afonsojramos** [comment]
Seems like such an edge case though. Remember that it is then another feature that we need to maintain and keep track of. I'd rather just focus on your second point 👀

**Comment by setchy** [comment]
Going to retire this idea for now.  Happy to reopen in future if there is enough interest.

As mentioned above, our newly reworked Account Management capabilities are a good solution for those with multiple account needs.
