### ISSUE TITLE
Instead of 400 pixels, make the height relative to the display height

### ISSUE THREAD

**Issue by a2sheppy** [gitify-app/gitify#433]
Currently, the popup for this menu extra on Mac comes up with a fixed height of 400 pixels. This is so very small and doesn't allow much of a window into the state of my GitHub activities. Instead, it should be based on the display height, taking the `workArea.height` value and subtracting a small amount to allow it to not just fill the height between menu bar and dock. I fiddled with this a bit and couldn't quite make it work, but didn't spend much time on it either (I tried some shortcuts that just didn't work). Figured I'd file this just in case others are interested in trying to make it happen.

**Comment by JakeSidSmith** [comment]
It would be nice to be able to resize the height, rather than a fixed value. 🙂  Not sure of the limitation of electron windows though.

**Comment by JakeSidSmith** [comment]
And I see you've just created #434 XD 👍

**Comment by a2sheppy** [comment]
I've also changed `resizable` to `true` in my local fork and everything works fine, though I doubt the size is saved. :)

**Comment by JakeSidSmith** [comment]
How is the positioning with resizable? I believe the reason this was not enabled originally was due to issues with the position of the window after resize (or something like that).

**Comment by a2sheppy** [comment]
Seems fine to me. You can of course resize the window from the top, so it looks weird, but that doesn't mean it doesn't work just fine.

**Comment by fdintino** [comment]
@JakeSidSmith I'm not so sure…it _was_ resizable before the 3.0 release. It got disabled in b8e8b169, but I'm not sure how intentional that was. Flipping `resizable: true` doesn't seem to have any ill effects.
