### ISSUE TITLE
Feature request: Include "reason" in native notification

### ISSUE THREAD

**Issue by madsnedergaard** [gitify-app/gitify#437]
## Proposal

The notification should include the reason (mention, review_requested, etc.) to make it easier as a user to know what the notification is about.

## Use case

In some cases, I want to ignore "mention" notifications and wait until I get a "review_requested" notification.

It would generally also be nice to get more context before opening the notification.

## Getting this done

I'd be happy to create a PR for this, I just wanted to make sure this was something you guys wanted before I started writing code :)

### Tasks

- [ ] Update [`raiseNativeNotification`](https://github.com/manosim/gitify/blob/21c25a886112eae899d111b33f9890a010e4ed5a/src/js/utils/notifications.ts#L28) function
- [ ] Test edge cases (long subject title, etc)

**Comment by codebytere** [comment]
I'd be fine with this unless @manosim would prefer to leave it as is :)

**Comment by manosim** [comment]
That sounds good - this would only apply when there is 1 new notification and not multiple right? If that's the case, feel free to make the change at

https://github.com/manosim/gitify/blob/b5b358579414b64de18e218095ab7e97175763fb/src/utils/notifications.ts#L66-L71 

There is also a helper to get a "friendly reason title" at 

https://github.com/manosim/gitify/blob/80dd20bd93cea5a44d526505c0e25a85af3107be/src/utils/github-api.ts#L21-L53

**Comment by setchy** [comment]
Not sure if this is still a desirable feature...

I had a few minutes so did a quick test locally of three ways the notification reason _could_ be added.  
![Screenshot 2024-01-19 at 3 53 22 PM](https://github.com/gitify-app/gitify/assets/386277/7cbab00e-1d72-40d9-8468-759fe07f2a68)

Open to feedback as well as alternate suggestions

**Comment by bmulholland** [comment]
IMHO it's a power user feature to use this. Most probably don't even think about the notification reason (I haven't even wrapped my head around what they mean, not that it's hard). For me at least, extra content in the notification would be extra noise I wouldn't want. So this should be an option... but I have concerns about adding too many options. See https://github.com/gitify-app/gitify/issues/728

**Comment by afonsojramos** [comment]
Agreed as well, let's keep it simple!
