### ISSUE TITLE
Feature Request: Display who did the thing that caused the notification

### ISSUE THREAD

**Issue by marblenix** [gitify-app/gitify#439]
what is shown:

"Updated X minutes ago"

what I'd like:

"Updated X minutes ago by <Author of the Pull Request>"

story: As a developer working with many teams on the same project, I currently get every notification for a repository. Currently I have to open every notification to see if it's something I need to pay attention to. It'd be nice if the gitify app showed me who made the change so I don't have to blow up my browser window with new tabs.

**Comment by codebytere** [comment]
Unfortunately the GitHub API is pretty rough around the edges for Notifications - [the result payload](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#list-repository-notifications-for-the-authenticated-user) doesn't contain that information at present. I'm fairly certain the GraphQL version does, but unfortunately it's not been exposed to 3rd party consumers and only the mobile app can access it at present.

**Comment by setchy** [comment]
i'll pick this up once https://github.com/gitify-app/gitify/pull/861 is merged
