### ISSUE TITLE
Feature request: To provide a button to go to logged in user profile directly

### ISSUE THREAD

**Issue by ankushduacodes** [gitify-app/gitify#476]
There is no way to reach github.com/<loggedin_username> from inside of the app to reach my own profile page.

**Comment by bergmul** [comment]
+1

When I first used the app I thought that the G icon or the Github icon would do this but both lead to gitify repo. 

It would be nice if clicking on the Github icon would open the loged in user's profile instead.

**Comment by alxhslm** [comment]
> It would be nice if clicking on the Github icon would open the loged in user's profile instead.
 
Totally agree - or if that's not possible, the GitHub icon should probably be removed as it's misleading.

**Comment by bmulholland** [comment]
We won't be adding UI complexity for minor workflow items that can easily be done in another way. You can get to your own profile using a browser bookmark or anything else -- you don't need Gitify for that. See also https://github.com/gitify-app/gitify/issues/655

**Comment by bmulholland** [comment]
I took a look and don't see the duplicate icon, just the Gitify one. Could be missing something -- but, if so, I'd love to improve consistency, so file a separate issue for that?
