### ISSUE TITLE
Feature request: Gitlab support

### ISSUE THREAD

**Issue by y-nk** [gitify-app/gitify#483]
I know it's a lot to ask, but could it (technically) be done?

**Comment by c4lliope** [comment]
+1, my choice is https://github.com/go-gitea/gitea

see http://gitea.com/api/swagger

**Comment by Dentrax** [comment]
Looking forward to this feature! Kind ping @manosim 🙏 Any planned roadmap?

**Comment by mlostekk** [comment]
This would be just awesome!
