### ISSUE TITLE
Feature Request: Pin Repos

### ISSUE THREAD

**Issue by bergmul** [gitify-app/gitify#486]
Hi, 

I love your app -- thanks for making our life a bit easier.

 It would be really cool, if we could pin repos in the app so that they show in the list (e.g. at the bottom). Clicking on the repo could then open the repo in the browser.

It is often a pain to navigate to a repo through the Github menu and this would be a really neat time saver.

**Comment by femto-code** [comment]
+1

**Comment by zoshigayan** [comment]
+1

**Comment by afonsojramos** [comment]
This would be overcomplicating the UI just a tad. If it gets more traction, maybe we can reconsider.
