### ISSUE TITLE
Dropdown in system tray is empty square

### ISSUE THREAD

**Issue by bradsk88** [gitify-app/gitify#489]
Gitify Version 4.2.0 (build from master branch)

Linux Versions:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.21.2
KDE Frameworks Version: 5.79.0
Qt Version: 5.15.2
Kernel Version: 5.10.19-1-MANJARO
OS Type: 64-bit
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX Vega
```

Steps to reproduce:
- Run Manjaro Linux with KDE installed
- Check out the gitify repo
- `yarn install`
- `yarn build`
- `yarn make:linux`
- cd into `dist/linux-unpacked/`
- Run `./gitify`
- Click the icon in the system tray

https://user-images.githubusercontent.com/2147630/112042500-3251f600-8b0d-11eb-851b-2d6842be37a5.mp4

**Comment by icron** [comment]
the same on macos on last master version

**Comment by icron** [comment]
> Gitify Version 4.2.0 (build from master branch)
> 
> Linux Versions:
> 
> ```
> Operating System: Manjaro Linux
> KDE Plasma Version: 5.21.2
> KDE Frameworks Version: 5.79.0
> Qt Version: 5.15.2
> Kernel Version: 5.10.19-1-MANJARO
> OS Type: 64-bit
> Graphics Platform: X11
> Processors: 16 × AMD Ryzen 7 3800X 8-Core Processor
> Memory: 31.4 GiB of RAM
> Graphics Processor: Radeon RX Vega
> ```
> 
> Steps to reproduce:
> 
> * Run Manjaro Linux with KDE installed
> * Check out the gitify repo
> * `yarn install`
> * `yarn build`
> * `yarn make:linux`
> * cd into `dist/linux-unpacked/`
> * Run `./gitify`
> * Click the icon in the system tray
> 
>  simplescreenrecorder-2021-03-22_12.49.53.mp4

Try to run `yarn run watch` it helped me. After that rerun `yarn npm start`

**Comment by Tiedye** [comment]
I'm seeing the same thing on popos 20.04 LTS except this is in the released version 4.3.0 using AppImage

![Peek 2021-11-08 16-05](https://user-images.githubusercontent.com/6187173/140817950-82131df9-6039-4a90-8fd8-a9cdebe9d9aa.gif)

**Comment by lfrancke** [comment]
Same on Arch using bspwm and polybar

**Comment by afonsojramos** [comment]
Keeping #499 in favour of this one as it is more complete.
