### ISSUE TITLE
No error when an SSO (single sign on) organization's login expires

### ISSUE THREAD

**Issue by kumar303** [gitify-app/gitify#490]
My GitHub organization [requires single sign on](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/enforcing-saml-single-sign-on-for-your-organization); occasionally something expires and I have to sign in again. When this happens in Gitify, there's no error. The notifications just stop working.

Could you provide some kind of error notification? At least then I'd know to go into settings, log out, and log back in (which fixes it).

In the meantime, I'm going to try and switch to an SSO-enabled token to see if that helps.

**Comment by setchy** [comment]
@kumar303 - v5.3.0 shipped today and includes updated error handling, including making it visible when credentials have expired 

![image](https://github.com/gitify-app/gitify/assets/386277/60564286-6666-4b51-9585-f31e55ea52b6)
