### ISSUE TITLE
[Ubuntu 20.04] No text or icons displayed when clicking the icon

### ISSUE THREAD

**Issue by brianrobt** [gitify-app/gitify#499]
I love this plugin and have used it on Mac and Windows, and now Ubuntu.  It's very functional on all the OSes.  The only problem that I have with my Ubuntu installation from the AppImage file is that there is no text displayed when I clicked the Gitify icon on my taskbar.  

## Bug on 4.2.1

When the blank dialog is hovered in the middle, the background changes, which indicates that there is text there but it's just white or invisible.  This occurs on all Appearance settings--"System", "Light", and "Dark. 

When the invisible text is clicked, I am brought to the expected window and the plugin works as expected.  It's completely functional but just looks like some text color needs to be changed.

Here is a screenshot: https://imgur.com/gallery/Xq291BG

**Comment by dprada** [comment]
The same here with Ubuntu 20.04.2 LTS.

**Comment by blackcat-917** [comment]
I have the same issue in KDE, you need to click on the void box to open the Gitify popup like here:


https://user-images.githubusercontent.com/53786619/120843254-2ef7d380-c56e-11eb-8e58-ae18b82dac93.mp4

**Comment by tbg** [comment]
Have the same issue, but wanted to add that even if the text showed up, why is the extra click needed? The list of notifications disappears every time I click on any of them, so every time it's click icon -> click empty space -> see the notification list -> click next one -> loop around. That can't be intended, right?

**Comment by improvshark** [comment]
Same issue on Manjaro - Gnome. Version 4.3.1-1 installed from AUR here.

**Comment by farfromrefug** [comment]
this is a know electron issue i think https://github.com/electron/electron/issues/14941

**Comment by JHK** [comment]
The issue mentioned seem to have been fixed. Maybe time to do a electron update?

**Comment by brianrobt** [comment]
This project hasn't been updated since 2021.  If I get time I will fork it and fix this issue myself.

**Comment by farfromrefug** [comment]
@brianrobt i have a working fork using tauri. I can push it someday

**Comment by brianrobt** [comment]
@farfromrefug I suppose.  At this point in time I think it'd be better just to fork it as its own repo completely and remove this one as the upstream.  The owner of this repo has been MIA for over a year now...

**Comment by farfromrefug** [comment]
@brianrobt sure we can maintain it from my fork, i dont mind. Just need to push it

**Comment by brianrobt** [comment]
@farfromrefug that would be awesome.  I've spent a couple hours trying to get it fixed but can't even get the .AppImage or .deb package to run properly.  It looks like it's getting stuck in an infinite loop in the main function.  Anyway, please let me know when you have it pushed.

**Comment by farfromrefug** [comment]
@brianrobt yes tauri will fix it all. Plus the app will be around 4mb :)

**Comment by afonsojramos** [comment]
Tauri would indeed be a major upgrade to this repo. Although it would probably be a ton of work to replicate the whole functionality.

**Comment by brianrobt** [comment]
@afonsojramos I'm still seeing this issue in 4.4.0.  I'll take a quick look to see if I can knock it out in a PR.

**Comment by afonsojramos** [comment]
Thank you @brianrobt! 
Regarding the Tauri rebuild I've very much for it @farfromrefug, but I think we should wait for Tauri v2 and in the meantime we'll keep maintaining this one.

**Comment by TriMoon** [comment]
Just tried to install the deb from the release page, and got a crash notification on Kubuntu 23.04 (KDE)...
I just uninstalled and removed the deb again, hope one day this will work in Kubuntu, till then take care :vulcan_salute:

**Comment by afonsojramos** [comment]
Any luck @brianrobt? I don't have a VM setup atm so it would help if someone with said setup could run locally.

**Comment by brianrobt** [comment]
@afonsojramos I haven't had a chance to even sit down and tinker yet.  Hopefully I will have some time tomorrow.

**Comment by brianrobt** [comment]
@afonsojramos I've tried playing around with it a bit in my local PopOS environment and can't find a workaround.  What's the behavior like on OS X; does the blank dialog appear at all?

**Comment by afonsojramos** [comment]
I've never seen a blank dialog on MacOS unfortunately (or rather, fortunately) 😕

**Comment by brianrobt** [comment]
@afonsojramos I see that this might have been fixed in electron 24.1.2.  Seeing that this project is using v13, that's probably going to break stuff.  It'd probably even be better to upgrade to the latest version if that's the route you want to go down.  I remember trying to do this a few months ago and running into a lot of issues just to get the app to run.

**Comment by afonsojramos** [comment]
Don't worry, we're working our way there 😁

**Comment by bmulholland** [comment]
@brianrobt if you want to help out on getting Gitify to the latest electron, currently I'm trying to remove electron/remote, via https://github.com/gitify-app/gitify/pull/654. I could use some help on that; my time is pretty limited. Once electron/remote's gone, upgrading to future electron versions will be easier :)

**Comment by setchy** [comment]
Closing as we're now on the latest election version. Gitify release pending
