### ISSUE TITLE
Big Sur doesn't hide the dock icon after a restart

### ISSUE THREAD

**Issue by pakerwreah** [gitify-app/gitify#507]
If we do a cold start (after shutting down completely) we see the app only in the menubar.
If we **restart** the system, the app icon reappears on the dock and I have to kill it and reopen.

macOS Big Sur 11.4 (20F71)

**Comment by hughlilly** [comment]
I'm seeing this as well, on 11.6 (20G165).

**Comment by afonsojramos** [comment]
I believe this no longer happens, closing.
