### ISSUE TITLE
Unable to Request Access to Organization after initial Launch

### ISSUE THREAD

**Issue by plflanagan** [gitify-app/gitify#516]
At initial launch there is the initial login flow. This included which organizations to get alerts on.

1. The request button didn't seem to do anything for me.
2. After this, I cannot find an opportunity to try requesting this access again.

**Comment by plflanagan** [comment]
In further investigation, the "request" did initiate Github to send an email to my account asking to confirm. This seems appropriate, and so this issue would then be that I had received no UI indication that the request was sent.

Github then had me go to `https://github.com/settings/connections/applications` to request the organization. This could be a useful piece of information to share (perhaps in the settings menu while open requests are still pending).

**Comment by afonsojramos** [comment]
This is already expected behaviour for dealing with Orgs with 2FA so adding this to the app would create some unecessary clutter. Closing for now.
