### ISSUE TITLE
[Question] How do you add new repository or organization to get notifications?

### ISSUE THREAD

**Issue by broccolism** [gitify-app/gitify#520]
Hi. Thanks for making such a great app.

I have a question about adding organization.
Recently I joined new organization and I cannot find how to get notifications from this organization.

I tried the way in FAQ here (https://www.gitify.io/faq),
but I could not find 'Gitify' tab in Settings page.

I guess this is related to access problem, but I cannot find how to allow access for new organization
that I joined after setting up all the other repository's access at the first time.

Hope anyone knows how to solve it.... thanks!

**Comment by codebytere** [comment]
@broccolism my personal recommendation would be to create and use a [Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)/ You can then authorize a given token for specific organizations as needed.

For example, I have a token created for Gitify that I've also authorized to access my notifications in Electron:
<img width="797" alt="Screen Shot 2021-11-02 at 2 46 02 PM" src="https://user-images.githubusercontent.com/2036040/139859738-21739369-4284-4cb2-a03b-29052e57c600.png">
