### ISSUE TITLE
Access Token Login not working with On-Prem GitHub Enterprise Servers

### ISSUE THREAD

**Issue by pbsureja** [gitify-app/gitify#527]
Hello,

My company uses a non standard Github Enterprise API : https://github.company.com/api/v3 instead of standard api.github.company.com which Gitify seems to refer to when connecting. Is there a way for me to modify configuration use actual api instead of the one created by Gitify ?

**Comment by ranma2913** [comment]
Can confirm this at my company too.  @pbsureja  I think you should update your Issue title though. It's not a non-standard api. In fact it IS standard for On-Prem Hosted GitHub Enterprise servers. See: https://docs.github.com/en/enterprise-server@3.1/rest/reference/oauth-authorizations

Maybe call the PR "Access Token Login not working with On-Prem GitHub Enterprise Servers"

When very closely reading the setup dialog we see "GitHub for Enterprise" which I'm guessing is a GitHub Cloud Service...
![image](https://user-images.githubusercontent.com/4295880/144090446-19cc8e21-8b8e-4fee-bfe9-5dadf68c2df9.png)

**Comment by ranma2913** [comment]
A way which seems to work is if you use Oauth App Method:
1. Create new OauthApp:
![image](https://user-images.githubusercontent.com/4295880/144091827-344577c5-3b14-4a32-abba-35edaa412e52.png)
2. Doesn't really matter what you configure here, but this is what I put:
![image](https://user-images.githubusercontent.com/4295880/144092406-9ada37d6-0ea3-4030-a604-d52910c49acc.png)
3. Create new ClientSecret

**Comment by LunaticMuch** [comment]
Has not been any more traction on this? I experience the same issue. Github Enterprise is not usable
