### ISSUE TITLE
[Feature Request] Black to white icon switch

### ISSUE THREAD

**Issue by younyokel** [gitify-app/gitify#532]
![image](https://user-images.githubusercontent.com/53343081/146090607-d1445fd5-905d-404f-8eee-ca50a0148bec.png)
On Windows, the dark theme icon doesn't contrast with dark theme taskbar. I suggest to add a toggle to change the color of the icon.

**Comment by Muetze42** [comment]
I changed the icons and the link in the lower left corner now leads to the GitHub homepage

https://github.com/Muetze42/gitify/releases/tag/1.0.0

![icon-idle](https://user-images.githubusercontent.com/26193232/225100102-d2c5659f-ccc4-498f-8d7c-ffa3a327f55a.png)

![icon-active](https://user-images.githubusercontent.com/26193232/225100093-4cb4ddf0-d932-4916-ace4-490942bf0daa.png)
