### ISSUE TITLE
Personal Access Token "could not be validated" with GitHub Enterprise

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [gitify-app/gitify#544]
Hi there. I can't use the "client ID / secret" login-method, as we don't usually have permissions to create GitHub Apps on our GHE.

However, PAT doesn't seem to be working either? I add our hostname (that is, indeed, the domain we access GHE through, correct? It's not some mutation of that, or a subdomain?); I generated a new token thru the GHE settings, and yet I'm still getting:

<img width="403" alt="Screen Shot 2022-04-05 at 3 21 41 PM" src="https://user-images.githubusercontent.com/200/161842408-225a2ede-64c3-4641-be0f-94d91e0dce3e.png">

Are there any debugging steps I can take? That error doesn't give a lot to go on, unfortunately …

**Comment by HenningCash** [comment]
This should already be fixed with #524 but there hasn't been any release since 15 Nov '21. I'm also waiting for this fix.
Maybe @manosim could create a new release, otherwise Gitify is unusable with GitHub Enterprise, unfortunately.

**Comment by RaphaelBarabas** [comment]
I'll stand in line.

Just installed via winget and found it won't connect via token. :sadcat:
