### ISSUE TITLE
More maintainers?

### ISSUE THREAD

**Issue by bmulholland** [gitify-app/gitify#545]
Seems like @manosim is too busy to stay on top of this repo, meaning that dependencies are out of date and [even simple fixes](https://github.com/manosim/gitify/pull/542) are going unreviewed and unmerged.

As a simple step, could others be granted access to merge changes? e.g. @codebytere seems to be more active.

**Comment by Araxeus** [comment]
It's really a shame, this app is quite nice

on a side note: you can get a custom version from my fork https://github.com/Araxeus/gitify/releases/tag/v4.3.2

**Comment by bmulholland** [comment]
@Araxeus I tried using your fork but ran into an error while building. Could you enable issues on the repo?

**Comment by Araxeus** [comment]
> @Araxeus I tried using your fork but ran into an error while building. Could you enable issues on the repo?

Sure, I just did

Just before installing, try running `yarn add menubar` to bump that package to the latest version which fixed some stuff

**Comment by bmulholland** [comment]
We can probably all switch over your fork, @Araxeus, if there's a way to get it released (maybe under a new name?)

**Comment by Araxeus** [comment]
I don't have time to maintain this project full time right now, but you are welcome to download the latest version on my fork
https://github.com/Araxeus/gitify/releases/tag/v4.3.2

**Comment by Araxeus** [comment]
I'd be up for creating an org and releasing a new version, need people interested.
meanwhile my fork is working fine for me :)

**Comment by cyberious** [comment]
Interested in this thread and where this is going.

**Comment by afonsojramos** [comment]
@bmulholland @Araxeus @cyberious I was developing a new feature for gitify and just noticed that this has been unmaintained for quite a while...

I have a bit of experience managing OSS organisations (currently manage https://github.com/spicetify) so I'm more than open to starting a new one and invite some of the recent contributors so we can get this project back from the dead! I'll try to get in contact with @manosim!

**Comment by afonsojramos** [comment]
@Araxeus @bmulholland @cyberious @setchy @jtzero and others that might be interested.

I was able to speak with @manosim, and you might already be seeing some results from it. The repo has been ported into the freshly created @gitify-app organisation and I do have write access now, so that @manosim can be a bit more hands-off/hands-on as he sees fit.

I did notice that actions were completely broken so I've managed to fix them and do a little upgrade on #566.

But small things aside, let's get PRs updated once we get the updated actions merged in, and focus on improving Gitify further!

**Comment by bmulholland** [comment]
Thanks to some amazing work by @afonsojramos, this one is resolved. Thank you, @afonsojramos! Thank you also, @manosim, for the project and the admin help in granting the necessary permissions.

**Comment by afonsojramos** [comment]
Stick around, because I have some ideas going forward for a potential 5.X 👀
But let's focus of 4.X now 😁

**Comment by setchy** [comment]
@afonsojramos - really enjoying seeing activity in this repo again.  

Let me know if there is anything I may be able to assist with.

**Comment by afonsojramos** [comment]
I've invited you all to have `write` permissions on the repo @bmulholland @setchy @Araxeus @hughlilly, this way you can also be active contributors in reviewing PRs and the like.

In the future, maybe we can create either a Discord or a chat in a similar so we can plan out the road forward.

Personally, I am waiting on Tauri v2 as it will enable this to become a way leaner app. Until then, let's keep iterating!

**Comment by setchy** [comment]
Awesome, thanks @afonsojramos. Sounds like a plan. 

Do you have any timeline on releasing a new version from the mainline, with all the recent updates and merges incorporated?

**Comment by bmulholland** [comment]
For homebrew, do we just submit a PR to update https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/g/gitify.rb ?

Looks like that's been done before: https://github.com/Homebrew/homebrew-cask/pull/76821/files

Happy to do the same now, as long it's not automated in some way and no one else is intending to do it

**Comment by afonsojramos** [comment]
We should definitely make it automated! @bmulholland

**Comment by bmulholland** [comment]
See https://github.com/gitify-app/gitify/issues/596 for that :)
