### ISSUE TITLE
Electron.app.Gitify Notification

### ISSUE THREAD

**Issue by barraIhsan** [gitify-app/gitify#546]
Instead of `Gitify`, the notification name is `electron.app.gitify`.
I think this is electron issue, BUT I think you can fix it following this stackoverflow answer
https://stackoverflow.com/a/64090072/12291570

**Comment by rogeruiz** [comment]
@AxoCode is this on Windows? I see the notification say `Gitify` when running this on macOS.

**Comment by AxoCode** [comment]
> @AxoCode is this on Windows? I see the notification say `Gitify` when running this on macOS.

Yes, I think

**Comment by Araxeus** [comment]
I have an open PR that fixes this https://github.com/manosim/gitify/pull/539

(unmerged for months)
