### ISSUE TITLE
Unable to click notifications in rare cases

### ISSUE THREAD

**Issue by Dentrax** [gitify-app/gitify#547]
I think this problem is a rare case and I could not able to click the notification. Its color sets to the background's when hovering with the mouse. But clicking on this does not work at all. And no idea why.

Version: `4.3.1`

![Screen Shot 2022-06-21 at 22 08 07](https://user-images.githubusercontent.com/16493751/174878780-5c7697f2-2512-4915-ab44-b2452b79e571.png)

**Comment by Dentrax** [comment]
Restarting the computer & Gitify does not solve the issue. I am still not able to click _that specific_ notification.

**Comment by Dentrax** [comment]
Just noticed the unclickable ones is the `discussion` neither issues nor pr.

**Comment by JakeSidSmith** [comment]
Duplicate of https://github.com/manosim/gitify/issues/521 ?

**Comment by Dentrax** [comment]
Seems duplicate, thanks.
