### ISSUE TITLE
Nothing showing when click on Tray icon

### ISSUE THREAD

**Issue by meanindra** [gitify-app/gitify#548]
I am using Pop!_OS 22.04 LTS
Nothing showing when I click on try icon(except a empty space)
![Screenshot from 2022-07-17 20-42-29](https://user-images.githubusercontent.com/36324543/179404801-5a1f9cbf-cb93-4f25-8ab4-b9cb5b00ddf8.png)

**Comment by hughlilly** [comment]
Can you open the Developer Tools (Ctrl - Shift - I) and see if there are any messages in the console, or if there is a document that isn’t rendering?

**Comment by afonsojramos** [comment]
Closing this one in favour of #499.
