### ISSUE TITLE
Bug: Does not change appearance with system

### ISSUE THREAD

**Issue by Ein-Tim** [gitify-app/gitify#550]
### Information:
This issue is a follow up to #496 which was closed as PR #515 was merged. However, I have to report that this issue still occurs. 

### Setup:
- MacBook Air 2020 (M1)
- macOS Monterey 12.5.1
- Gitify v. 4.3.1

### Describe the issue:
When setting the appearance setting to "System", the appearance of Gitify never changes the appearance with the system. So even if the system changes to light mode, Gitify stays in dark mode (and the way around)
### Expected behavior:

Gitify should change its appearance with the appearance of the system.

### Ping
@codebytere you authored #515 so maybe you want to take a look at this follow-up too?

**Comment by hughlilly** [comment]
Even though it’s of no help, I thought I would report that it’s working OK for me on a MacBook Pro (Retina, 13-inch, Early 2015), running the same OS and app versions (macOS Monterey 12.5.1, Gitify v. 4.3.1).

**Comment by JakeSidSmith** [comment]
@Ein-Tim I'm running exactly the same model as you and Monterey 12.4. After a change to system settings if I close and re-open Gitify the theme updates. Are you seeing the same?

**Comment by Ein-Tim** [comment]
Hey @JakeSidSmith, thanks for your comment!

I just restarted my Mac to test if that works now and I can confirm that it now works for me too. Sorry for any confusion caused.

**Comment by JakeSidSmith** [comment]
You might want to leave this issue open, as ideally it'd change instantly.

@hughlilly do you need to close and re-open Gitify for system theme changes to make a difference?

**Comment by JakeSidSmith** [comment]
So, I just had a little play.

In Gitify "System" was selected. Changing the theme in the system did not take affect in Gitify unless I closed and re-opened it.

I then changed the option in Gitify to "Dark", "Light", and then back to "System".

Now changing my system theme immediately takes effect in Gitify. 🤔 

I'm guessing either my setting for "System" was not stored, and the UI just defaults to appear as if "System" is selected, or there's some weird edge case where after some time it stops getting events about the System theme changing. 😬

**Comment by JakeSidSmith** [comment]
I think maybe this line...

https://github.com/manosim/gitify/blob/75eb1c83e7738ad6ed5e61d79b6f4a9ef28c0049/src/routes/Settings.tsx#L23

...should be updated to be "if the theme is not explicitly dark and the theme is not explicitly light then match the system theme".

**Comment by hughlilly** [comment]
> In Gitify "System" was selected. Changing the theme in the system did not take effect in Gitify unless I closed and re-opened it.
> 
> I then changed the option in Gitify to "Dark", "Light", and then back to "System".
> 
> Now changing my system theme immediately takes effect in Gitify. 🤔

Yes, I just had this exact same experience when testing:


https://user-images.githubusercontent.com/12046008/191845437-57b363b0-463d-422c-8a63-7f62393102c9.mov

**Comment by setchy** [comment]
@hughlilly @JakeSidSmith - can you please re-test on [v4.4.0](https://github.com/gitify-app/gitify/releases/tag/v4.4.0).

**Comment by JakeSidSmith** [comment]
I'm now on Ventura 13.4, but it appears to be working nicely in 4.4.0. 😁

**Comment by bquorning** [comment]
This issue still happens for me on v4.6.1, and on `main` (SHA 2f2520965f521519aa6ef1064aa8d2ddd33d1a11) with Ventura 13.6.3.

**Comment by setchy** [comment]
Thanks @bquorning - interesting - I wasn't able to reproduce on `main` Sonoma 14.4.  I'll re-open this ticket. 

Would you mind sharing a brief recording / gif recreating it 🙏

**Comment by setchy** [comment]
@bquorning - we just released v5.0.0.  If you have a moment, could you kindly retest with this version and share your experience

**Comment by bquorning** [comment]
I haven’t seen the issue since upgrading to v5.0.0 last week. Thank you 🙏🏼

**Comment by setchy** [comment]
> I haven’t seen the issue since upgrading to v5.0.0 last week. Thank you 🙏🏼

Great news.  Thanks for confirming @bquorning
