### ISSUE TITLE
Clicking does not take me to the relevant item

### ISSUE THREAD

**Issue by samsrabin** [gitify-app/gitify#558]
Clicking on a notification no longer takes me to the relevant page on GitHub. Instead, nothing happens (or it's marked as read if I have that enabled.)

(macOS 12.6, Gitify 4.3.1)

**Comment by hughlilly** [comment]
Getting this too, on v.4.3.1 on macOS 12.6.1 (21G217).

**Comment by hughlilly** [comment]
A non-scientific test I just did sorta implies that ci-activity notifications don’t open a link, but comments and other types do?

**Comment by samsrabin** [comment]
Hmm, that doesn't match my experience. The only notifications I get are comments etc.

**Comment by bmulholland** [comment]
Closing this as stale. Let me know if it still happens on v4.4.0.

**Comment by mstyles** [comment]
I'm on the latest release (5.12.1) and this is happening for me. It seems to only affect private repos? Public repos appear to open fine.

**Comment by setchy** [comment]
Thanks for sharing @mstyles.  

So to confirm, when you receive a notification from a private repository, it shows in Gitify.  However, when clicking on the notification to open in browser it does nothing?  Is there anything in the logs that stands out?

**Comment by mstyles** [comment]
Yes, that's exactly it! Except it does do "something" in that it still marks it as read and all that, but it just doesn't actually open it up in the browser. As far as logs go, it looks like the request for PR details (e.g. `GET https://api.github.com/repos/foo/bar/pulls/20138` is returning a 404 from github:
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/pulls/pulls#get-a-pull-request",
  "status": "404"
}
```
and then in the logs it just says:
```
11:25:11.511 › Failed to get html url
```

**Comment by mstyles** [comment]
I'm sorry, I've answered my own question and I feel dumb. My token was just expired... Sorry for the hassle!

**Comment by setchy** [comment]
All good - thanks for reporting back.
