### ISSUE TITLE
Add “Mark all as done” to top of notifications page

### ISSUE THREAD

**Issue by hughlilly** [gitify-app/gitify#559]
When there are notifications from multiple repositories, there is no “Mark all as done” option, only a “Mark all as done” option _for each repository_. It would be good to have a ‘global’ tick that marked all displayed notifications as done, across all repositories.

**Comment by afonsojramos** [comment]
I'm not sure this is actually a good thing. Considering the absence of other people's feedback, I'm going to assume the community agrees here.
