### ISSUE TITLE
Filter notifications by reason

### ISSUE THREAD

**Issue by hughlilly** [gitify-app/gitify#560]
I’d like to be able to filter notifications by reason. For example, I’d like Gitify to contain notifications for everything _except_ `ci activity`. In other words, I’d like to be able to negate this search: https://github.com/notifications?query=reason%3Aci-activity

I don’t know if this is possible with the API.

**Comment by y-nk** [comment]
This 👌 v. cool

**Comment by afonsojramos** [comment]
This would be better done in the UI tbh. Just filtering out the ones you don't want. Should be rather easy!
