### ISSUE TITLE
[BUG] There's a broken icon when used with GHE

### ISSUE THREAD

**Issue by LunaticMuch** [gitify-app/gitify#564]
I found this broken icon, and it feels like a bug.

I am happy to work and fix it, but wondering if this project is being maintained or not as the feeling seems no.
@manosim do you look for help?

![Screenshot 2023-03-21 at 17 56 51](https://user-images.githubusercontent.com/1659414/226699365-17ac8be2-b1a9-46e1-b9df-562f154da00b.png)

**Comment by afonsojramos** [comment]
Hey @LunaticMuch! Does this still happen? Do you happen to know which icon this might be?

**Comment by bmulholland** [comment]
The project indeed was not moving, but @afonsojramos has picked it up and is getting things moving again 🎉

**Comment by LunaticMuch** [comment]
Thanks. I updated today to version v4.4 and the bug is still there. Can I help some debug?

**Comment by afonsojramos** [comment]
@LunaticMuch Yeah, if we could know what was the type of notification that would be great! But it is indeed weird because we have defaults in place for "unknown" types of notifications.

**Comment by setchy** [comment]
I suspect in your situation, the following is either returning null, or a URL that is perhaps behind some network security controls https://github.com/gitify-app/gitify/blob/ad655b9f664cbb7585e907a54c76cc50d49dfff9/src/components/Repository.tsx#L39

@LunaticMuch - you should be able to verify by calling `/notifications` and check what value is returned for `repository.owner.avatar_url`
