### ISSUE TITLE
Ignore specific notifications

### ISSUE THREAD

**Issue by steebchen** [gitify-app/gitify#591]
### 📝 Provide a description of the new feature

It would be cool if you could ignore specific notifications, such as by author of a PR. Specifically, I want to ignore notifications from @dependabot, both comments from @dependabot but also PR creations/changes from @dependabot.

**Comment by setchy** [comment]
@steebchen - thanks for the suggestion. I have an implementation ready to contribute which can ignore any notification raised by a `Bot` usertype such as @dependabot @renovatebot @vercelbot etc.  

Does this sound like a good fit for your use-case?

**Comment by steebchen** [comment]
Awesome, yep sounds good to me! 🙌
