### ISSUE TITLE
Automate Homebrew releases

### ISSUE THREAD

**Issue by bmulholland** [gitify-app/gitify#596]
This is an issue to work through what's needed to release to Homebrew automatically

[Homebrew looks for this URL](https://github.com/Homebrew/homebrew-cask/edit/master/Casks/g/gitify.rb): `https://github.com/gitify-app/gitify/releases/download/v#{version}/Gitify-#{version}-universal-mac.zip`

That looks in Downloads for a zip of, presumably, the compiled universal mac app. That seems to be one of the assets that was attached to prior releases, e.g. https://github.com/gitify-app/gitify/releases/tag/v4.3.1

The new release only has two assets; there's no compiled app to link to.

@afonsojramos, I know you changed the release and build -- can you think of anything that would have changed this part?

**Comment by afonsojramos** [comment]
Unfortunately this is an issue with the release process altogether. All of the changes that I've made was to attempt to fix the issues that I've encountered. 
So far I've fixed a few, but the release process seems to be a bit broken at the moment.

There were releases not triggering any job, [missing GitHub tokens](https://github.com/gitify-app/gitify/actions/runs/6198353343/job/16828626083), and now we're left to [two main issues](https://github.com/gitify-app/gitify/actions/runs/6198821574).

Windows/Linux build not uploading to the existing release:
<img width="1039" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/446cb650-a357-4899-91e7-99ff7a39e02e">

MacOS build missing the `CSC_KEY_PASSWORD`:
<img width="1076" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/5e7991b7-f219-49eb-a987-aec9e6d7b09d">
