### ISSUE TITLE
Release process is broken

### ISSUE THREAD

**Issue by afonsojramos** [gitify-app/gitify#597]
While attempting to get new releases for Gitify going, I've encountered a few hurdles in the release process. I've already made some changes to attempt to fix the issues that I've encountered. But I haven't been able to fix all of them, and, as such, I've rolled back the release of version `v4.4.0`.

There were releases not triggering any job, [missing GitHub tokens](https://github.com/gitify-app/gitify/actions/runs/6198353343/job/16828626083), and now we're left to [two main issues](https://github.com/gitify-app/gitify/actions/runs/6198821574).

Windows/Linux build not uploading to the existing release:
<img width="1039" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/446cb650-a357-4899-91e7-99ff7a39e02e">

MacOS build missing the `CSC_KEY_PASSWORD`:
<img width="1076" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/5e7991b7-f219-49eb-a987-aec9e6d7b09d">

Additionally, we want to automate the release to Homebrew if possible, as defined in #596.

**Comment by bmulholland** [comment]
@afonsojramos could you link to the builds that failed there? I have a couple hypotheses to check about what could have happened, based on several fights with Github secrets management

**Comment by afonsojramos** [comment]
They're linked in the second paragraph @bmulholland. My suspicion is that the step itself was trying to create a release, which is weird, because otherwise there would always be 2 out of the 3 builds that would fail, since one would create it first always.

Probably needs investigation on `electron-builder`.

**Comment by bmulholland** [comment]
The release was pulled from Github, so I can't check the details... did you follow the steps here? https://www.electron.build/configuration/publish.html#recommended-github-releases-workflow

**Comment by bmulholland** [comment]
I guess that's also documented here: https://github.com/gitify-app/gitify#releases ...

**Comment by afonsojramos** [comment]
oh wow @bmulholland 😮‍💨 🤦 I'm going to lay down on the grass for a bit now ☠️ 

MacOS one is still failing though. I'll close this one as it is no longer relevant and focus on the real issue which is the missing secret.

**Comment by afonsojramos** [comment]
<img width="899" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/85c50756-c0f0-492d-b556-2c9c068bc610">

FYI Linux and Windows ⬆️
