### ISSUE TITLE
No New notifications after update to 4.4

### ISSUE THREAD

**Issue by eMerzh** [gitify-app/gitify#624]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Hey 👋 

thanks for updating this app 🚀  

it seems that me and a few others have issues to retrieve new notifications.

i relogged, restart.. doesn't seems to help

### 🪜 Steps To Reproduce

1. start app
2. get notification
3. nothing happens

### ℹ System Info

```Markdown
Mac 13.5.2 (22G91) 
latest 4.4.0
```

**Comment by afonsojramos** [comment]
Do you have notifications enabled for the app on MacOS?

**Comment by eMerzh** [comment]
oh sorry that wasn't clear ... i meant github notifications 😬 ....
funnyliy enough i got at notif for this one .... now that i try to redo that i can't... 

if you want a screenshot :

<img width="795" alt="Capture d’écran 2023-09-28 à 20 37 45" src="https://github.com/gitify-app/gitify/assets/177003/4a0b4a48-869a-4577-ba7d-b65d94760938">

**Comment by AlexanderHieser** [comment]
I have the same problem. Going back to v4.3.1 solved the issue.

**Comment by eMerzh** [comment]
@afonsojramos hum ... it seems to be related to colors indeed 
(but i like colors 🥺)

ftr I used the token to login...

**Comment by afonsojramos** [comment]
I think that for the colors it may require the `repo` scope, which the previous version did not have. The `repo` scope was introduced here: #538 
I'll try to take a look if there is something that can be done.

**Comment by dberuben** [comment]
same issue

**Comment by cleardemon** [comment]
H there, just wanted to confirm that either disabling colours or updating the token with `repo` scope makes notifications appear in Gitify again in 4.4.

**Comment by ponkio-o** [comment]
Hi, I'm having the same problem with Github Enterprise Server. I tried `repo` scope permission granted but it didn't show up.
Does anyone else have a similar problem??

**Comment by bmulholland** [comment]
@rbclark Yes, you got it, see https://github.com/gitify-app/gitify/issues/624#issuecomment-1741007292

Unfortunately we don't have a flow to request updated scopes, and doing that would be a bunch of work. We could add a fallback to not use colors, though that also wouldn't be great.

**Comment by rbclark** [comment]
@bmulholland I think the most clear thing would be logging out the user if they don't have the proper scopes and requiring them to re-authenticate. It took me the whole week of not getting notifications before I investigated since I didn't realize anything was wrong since it was silently failing.

**Comment by bmulholland** [comment]
Yeah that's an easy enough idea. @afonsojramos what do you think?

**Comment by bmulholland** [comment]
Okay I'm still learning the codebase so that solution needs a bit more understanding than I can quickly do. I've instead created #660 to default the colors to off, and flag in the settings that re-auth is needed, until we can apply that.

**Comment by kusold** [comment]
🐛 Using a Github Enterprise instance with a PAT that has `notifications, read:user, repo` scopes, Gitify does not work with colors enabled. If I disable colors and restart the app, it begins working again.

There might be an additional edge case that only applies to GHE instances.

Side Note: It's exciting to see new releases of this app. Thanks for all the hard work.

**Comment by afonsojramos** [comment]
@kusold this is an edge case that has already been fixed. Maybe it is worth it to do another release.

**Comment by brunogeronimo** [comment]
Hey 🙂,
As a feedback, it would be great not to force users to grant `repo` permission, since the app works perfectly fine just with `notifications` scope, even though we lose support for colors in this case.

Some companies using GitHub Enterprise for example might be picky in terms of being OK with granting `repo` and other permissions on the token, specially if the app works just fine without any of them.

**Comment by FranCarstens** [comment]
@brunogeronimo, 4.4.0 works for me when creating a new access token without the "repo" permission, and "use colors" unchecked.

**Comment by bmulholland** [comment]
@brunogeronimo We're not logging users out. See https://github.com/gitify-app/gitify/pull/673

It's been a bit slow coming, we've both got other stuff going on, thanks for all your patience.
