### ISSUE TITLE
Git hooks for common checks

### ISSUE THREAD

**Issue by bmulholland** [gitify-app/gitify#647]
Would we be open to adding husky hooks, e.g. for tsc and prettier styles? I keep accidentally checking in poorly formatted code and would appreciate a faster feedback loop.

**Comment by bmulholland** [comment]
WDYT @afonsojramos ?

**Comment by afonsojramos** [comment]
Considering that we already check these in CI and these hooks' purpose would be to purely help with the development experience, I'm all for it!
