### ISSUE TITLE
Document non-goals of Gitify

### ISSUE THREAD

**Issue by bmulholland** [gitify-app/gitify#655]
What things won't we do, and why? Let's write them down.

I'll start by collecting them here. We can add to the README later.

* Operating-system level features
  * Do not disturb, including on schedules. https://github.com/gitify-app/gitify/issues/416#issuecomment-1746480130
  * Persistent notifications like https://github.com/gitify-app/gitify/issues/281. e.g. macOS has Alerts, instead of Banners, which make them persistent
* Seeing past notifications. This is a tool for monitoring new notifications, not seeing old ones, which can be seen at https://github.com/notifications.
* Specific UX/UI changes that add options and/or visual complexity for minor workflow improvements. e.g. https://github.com/gitify-app/gitify/issues/358, https://github.com/gitify-app/gitify/issues/411 and https://github.com/gitify-app/gitify/issues/979
* UI for something that isn't core to Gitify, and/or can be trivially done another way. e.g. https://github.com/gitify-app/gitify/issues/476 and https://github.com/gitify-app/gitify/issues/221
* Support anything other than Github. Doing so would be a major undertaking that we maaayyy consider in future, but it would be a ton of work and there's so much tied to Github right now that it's not something I'd want to maintain.

**Comment by bmulholland** [comment]
I've seen this in the README of other projects. WDYT?

**Comment by setchy** [comment]
my 2 cents:  a brief mention in the README with a link to another detailed MD file
