### ISSUE TITLE
Release Notifications: Link to release tag instead of releases page

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#670]
### 📝 Provide a description of the new feature

I commonly use release notifications, and at present these are linked to https://github.com/{{org}}/{{repo}}/releases

This FR card is to enhance the logic to link to the specific release tag for the notification, eg: https://github.com/{{org}}/{{repo}}/releases/tag/{{releaseTag}}

**Comment by bmulholland** [comment]
> FR card

Is this another term for "Feature Request via Github Issue"?
