### ISSUE TITLE
Add option to launch minimized

### ISSUE THREAD

**Issue by killermoehre** [gitify-app/gitify#678]
### 📝 Provide a description of the new feature

On Linux, I added `gitify` to my DEs autostart. Now, the window pops up during every start instead of being started in the background.

As there is no `--help` switch on the CLI, I can't check for any `--background`.

**Comment by setchy** [comment]
@killermoehre - i'm not a daily linux user.  which flavor are you using?  

Are you able to use Window Rules to manage this locally?

**Comment by setchy** [comment]
@killermoehre - if you have a moment would you mind testing [this fix](https://github.com/gitify-app/gitify/pull/1097#issuecomment-2102656812) please
