### ISSUE TITLE
On Linux app doesn't check if FirstRun dir exists

### ISSUE THREAD

**Issue by killermoehre** [gitify-app/gitify#679]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

On Linux, I had to create `$HOME/.config/gitify/FirstRun/` by hand to make the app happy.

### 🪜 Steps To Reproduce

1. make sure `$HOME/.config/gitify/FirstRun` doesn't exists.
2. start `gitify`
3. Enjoy an error message

### ℹ System Info

```Markdown
OS: Arch Linux
Project Version: 4.4.0.r3.0fc4e8f (`main` branch checkout)
```

**Comment by hrqmonteiro** [comment]
Will someone look into this? The app is unusable on Linux (!!?)

**Comment by setchy** [comment]
https://github.com/gitify-app/gitify/blob/1396b6650be639951160ed773c487cb5b49ba412/first-run.js#L37-L51 should be creating this directory if not present.
