### ISSUE TITLE
Feature request: add a new "Mark as done on click" setting

### ISSUE THREAD

**Issue by adufr** [gitify-app/gitify#714]
### 📝 Provide a description of the new feature

This feature would be possible thanks to the newly added `Mark notification as done` API endpoint (see #500)

It would basically do the same thing than the old `Mark notification as read on click` setting which is now obsolete (#712)

### ➕ Additional Information

I'm willing to implement this, but I'd like my other PR #500 to be merged before as it will use shared code/functions (I might open a stacked PR..)

**Comment by rpuncel** [comment]
This would be hugely helpful; GitIfy is super useful but the "Done" feature in GitHub Notification Center is critical for me.  Right now, I'll let Gitify make me aware there's a notification, but then still open the GitHub Notification center to actually read the notification.

**Comment by adufr** [comment]
I'm closing this as the feature has been merged 🎉

**Comment by fredrikaverpil** [comment]
Was there ever a release that included this feature?

**Comment by adufr** [comment]
@fredrikaverpil not yet :(

**Comment by setchy** [comment]
@fredrikaverpil @adufr - we need to fix this before our next release #https://github.com/gitify-app/gitify/issues/696
