### ISSUE TITLE
Access to microphone requested. For what?

### ISSUE THREAD

**Issue by samuelb** [gitify-app/gitify#743]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

Hi

Since a few days, macOS prompts me to allow access to the microphone for Gitify. This popup appears every time Gitify shows me an notification about a new or updated PR. 

I find this suspicious, since this tool shouldn't require the microphone for anything. Or does it?

I installed Gitify with Homebrew and the version is 4.6.1. My files in the /Applications/Gitify.app folder matches the once from the downloadable zip from Github.

Why does Gitify require microphone access?

### 🪜 Steps To Reproduce

Not sure if this is a occurrence specific on my system and therefore I don't know really how to reproduce this on any other system. I basically installed and configured Gitify. Then it starts to prompt for microphone access when PR activity in my repos would show a notification in Gitify. 

### ℹ System Info

```Markdown
MacBook Air M1 macOS 14.3
```

**Comment by bmulholland** [comment]
This is weird. I'm also on macOS 14.3 with Gitify 4.6.1 installed via Homebrew, and I don't experience it. I checked Settings > Privacy > Microphone, and Gitify isn't listed. I don't know all the lines of the codebase, but I'm pretty confident we haven't added something to do with a mic in recent releases. Given you're the only person who's reported this, it's more likely something about your setup.

**Comment by mthines** [comment]
I get the same request and do not like it

**Comment by setchy** [comment]
I found this when searching the apps plist

```
adam@mac ~ % grep Microphone -A 1 /Applications/Gitify.app/Contents/Info.plist 

    <key>NSMicrophoneUsageDescription</key>
    <string>This app needs access to the microphone</string>
```

@afonsojramos - could this be linked to the warning in the [v4.6.1 release notes](https://github.com/gitify-app/gitify/releases/tag/v4.6.1)?

**Comment by setchy** [comment]
Searching for all mentions of access returns

```
adam@air ~ % grep access -B 1 /Applications/Gitify.app/Contents/Info.plist

    <key>NSBluetoothAlwaysUsageDescription</key>
    <string>This app needs access to Bluetooth</string>
    <key>NSBluetoothPeripheralUsageDescription</key>
    <string>This app needs access to Bluetooth</string>
    <key>NSCameraUsageDescription</key>
    <string>This app needs access to the camera</string>
--
    <key>NSMicrophoneUsageDescription</key>
    <string>This app needs access to the microphone</string>
```

none of which are part of our entitlements file - https://github.com/gitify-app/gitify/blob/main/entitlements/entitlements.mac.plist

**Comment by adufr** [comment]
> <key>NSMicrophoneUsageDescription</key>
>     <string>This app needs access to the microphone</string>

I tried searching for this too, the only place it came up was in `node_modules/electron/dist/Electron.app/Contents/Info.plist` 🤔

**Comment by bmulholland** [comment]
Yeah and the first place I checked on was [Electron's setting to ask for mic](https://stackoverflow.com/questions/56713994/request-microphone-permission-in-electron), but there's nothing in this repo about that. Super weird. Is there something about the build process that introduces it?

**Comment by afonsojramos** [comment]
That's very weird... I'll see if the switch to electron forge fixes this by any chance.

**Comment by bmulholland** [comment]
I also wonder if the electron upgrades will help.

**Comment by samuelb** [comment]
I discovered that the microphone permission prompt wont show up if "Play sound" in Gitify is turned off or when having a bluetooth headset connected.

**Comment by bmulholland** [comment]
Just to make sure I understand: you're saying this prompt only happens if:
1. "Play Sound" is enabled in Gitify, AND
2. You have a Bluetooth Headset connected, AND
3. You receive a new notification

Is that right?

**Comment by samuelb** [comment]
1. "Play Sound" is enabled in Gitify, AND
1. You **don't** have a Bluetooth Headset connected, AND
1. You receive a new notification

Sorry when my wording was not clear in my previous message.

**Comment by bmulholland** [comment]
Wow super weird. Thanks for the clue!

**Comment by setchy** [comment]
Labeling this as `documentation`.  We can look to update both the README, and the FAQ for gitify.io
