### ISSUE TITLE
Login Button Does Not Work

### ISSUE THREAD

**Issue by mzagaja** [gitify-app/gitify#747]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

When I try to login to Github Nothing happens.

### 🪜 Steps To Reproduce

1. Click the "G" in the menu bar
2. Click "Login to Github"

### ℹ System Info

```Markdown
MacBook Pro 16 inch 2019
MacOS 14.3
```

**Comment by jtzero** [comment]
using a personal access token still works if you need a workaround

**Comment by hansolljeong** [comment]
> using a personal access token still works if you need a workaround

Your comment helped me too. Thank you.

But I have one question.
Do I have to create a new token? I used the option for the token I already had and it didn't work, so I created a new token and logged in and it worked fine.

**Comment by adufr** [comment]
@hansolljeong It depends on the permissions associated with your token; your old token probably didn't have the correct permissions.

On a side-note, it is a better practice not to re-use an existing token, but to have a dedicated token for each specific purposes, this way you can have more control on the permissions associated to each token, which means better security! 😉

**Comment by mzagaja** [comment]
This issue is persistent in the new version.

**Comment by bmulholland** [comment]
Yes, we need to switch the 2FA to be via a browser. I haven't had time to do it: https://github.com/gitify-app/gitify/pull/654

**Comment by maxheyn** [comment]
I am still experiencing this issue as of April 2024. I've tried this on the latest version v5.2.0, and also downgrading back to the version I was on previously, v4.6.1, and the button doesn't work on either.

**Comment by setchy** [comment]
> organizations behind SSO with the access token login
@maxheyn - is this GitHub Enterprise Cloud, or GitHub Enterprise Server?

**Comment by maxheyn** [comment]
> > organizations behind SSO with the access token login
> 
> @maxheyn - can you share if this is GitHub Enterprise Cloud or GitHub Enterprise Server?

@setchy Neither, it's just a GitHub organization using SAML SSO for authentication.

**Comment by eseiker** [comment]
> I am still experiencing this issue as of April 2024. I've tried this on the latest version v5.2.0, and also downgrading back to the version I was on previously, v4.6.1, and the button doesn't work on either.
> 
> Idk if this is related but I can't get notifications for organizations behind SSO with the access token login, which I need for my work :(

4.6.1 didn't work for me neither, but downgrade to 4.4.0 worked and kept logged in after updating back to 5.5.0

**Comment by afonsojramos** [comment]
But the token based login should work! Have you tried to configure SSO in the tokens menu?
<img width="305" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/4a5c8f4a-fdca-45a9-9841-8675462dcd42">
