### ISSUE TITLE
Feature request: show notifications count next to icon in menubar

### ISSUE THREAD

**Issue by adufr** [gitify-app/gitify#750]
### 📝 Provide a description of the new feature

It would be nice to show the notifications count next to the Gitify icon in the menubar

~~From what I saw it's an image, so it should be possible to dynamically generate one by using some 3rd party library.~~
EDIT: Use the `menubarApp.tray.setTitle()` API

For example with the "Reminders MenuBar" icon:
<img width="35" alt="image" src="https://github.com/gitify-app/gitify/assets/26418696/53b86b3d-7d30-489a-ac9e-2409bb8c7f6c">
<img width="39" alt="image" src="https://github.com/gitify-app/gitify/assets/26418696/d88d7f70-3049-42cf-95a9-667557b6ae32">

### ➕ Additional Information

I'd like to work in this if you approve the feature request! 😉

**Comment by bmulholland** [comment]
This is probably down to personal preference and workflow. For me, I like the simplicity. See also https://github.com/gitify-app/gitify/issues/728

**Comment by adufr** [comment]
> This is probably down to personal preference and workflow. For me, I like the simplicity. See also #728

I agree, some people might not want this feature, but IMO it's sad to prevent other people from benefiting from it; so a setting could be the solution (+ the setting would be a simple checkbox so it wouldn't bring much complexity)

I read #728 and gave my opinion there!

**Comment by setchy** [comment]
I think this would be fine so long as the feature is behind a settings flag.  Personally, I like the simplicity of the different colored icon.

**Comment by adufr** [comment]
Thank you both for your input 😄 
I'll start working on adding this setting as soon as I have some time!

**Comment by setchy** [comment]
This feature was released today in v5.2.0
