### ISSUE TITLE
Switch Validate PR Name custom linting workflow for Semantic PRs GitHub App

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#808]
### 📝 Provide a description of the new feature

Consider switching the Validate PR Name linting workflow with the following GitHub Ap https://github.com/marketplace/semantic-prs

**Comment by setchy** [comment]
_Note: requires a organization admin to install_

**Comment by afonsojramos** [comment]
What are the advantages here?

**Comment by setchy** [comment]
Less self-managed regex.  I've had a number of PRs the last few days fail our workflow.

Example: https://github.com/gitify-app/gitify/actions/runs/7979926565/job/21789354134?pr=805
PR Title was: `test(github-api): fix typo in notification color test`
