### ISSUE TITLE
feature: support grouping notifications by date or repository

### ISSUE THREAD

**Issue by setchy** [gitify-app/gitify#836]
### 📝 Provide a description of the new feature

https://github.com/notifications supports displaying notifications in two ways
* date
* repository

Currently gitify always will group by repository.  

This feature suggestion is to match the experience of the official GitHub web interface

**Comment by AltinGruda** [comment]
Hey, can I work on this?

**Comment by setchy** [comment]
> Hey, can I work on this?

Absolutely!  That would be greatly welcomed 🙏
