### ISSUE TITLE
Image not found v5

### ISSUE THREAD

**Issue by nandi95** [gitify-app/gitify#918]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

After updating to v5 from 4.6.1 using brew I constantly get an error:
```
Uncaught Exception:
Error: Failed to load image from path '/Applications/Gitify.app/Contents/Resources/app.asar/assets/images/tray-idleTemplate.png'
at IpcMainImpl.<anonymous> (/Applications/Gitify.app/Contents/Resources/app.asar/main.js:85:25)
at IpcMainImpl.emit (node:events:513:28)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81099)
at EventEmitter.emit (node:events:513:28)
```

### 🪜 Steps To Reproduce

Update from 4.6.1 to v5 using homebrew

### ℹ System Info

```Markdown
M1
os: latest
```

### 📸 Screenshots

<img width="261" alt="Screenshot 2024-03-21 at 09 03 09" src="https://github.com/gitify-app/gitify/assets/41805560/01dbed28-5841-489a-8bc7-c41d47a3f70d">

**Comment by nandi95** [comment]
It seems to work when reinstalled.

**Comment by setchy** [comment]
Thanks for reporting @nandi95 . 

I had a similar, but slightly different experience. When updating via homebrew from 4.5.1 to v5.0.0, I got a similar prompt ~5 times. The updated app worked fine without the need to reinstall. 

We'll keep our eyes out for other similar reports

**Comment by setchy** [comment]
I upgraded two devices to v5.1.0 this morning.  One device was a smooth upgrade, another had the same `image not found` prompts.  relaunching the app worked.  we'll need to dig a bit deeper it seems.

**Comment by setchy** [comment]
The maintainers haven't seen this issue reoccur today after performing v5.2.0 upgrades.  Will close this issue, but happy to reopen if/when it may reappear

**Comment by setchy** [comment]
My latest working theory is this error will occur when
- Gitify is running
- performing a `brew upgrade` to update outdated casks.

Reading through the [Brew cask guides](https://docs.brew.sh/Cask-Cookbook), the below call-out for `quit` commands seems to correlate with our experience
_> (does not run when uninstall is initiated by brew upgrade or brew reinstall)_

**Comment by setchy** [comment]
Proposing some changes to our cask file to should help 🤞  this: https://github.com/Homebrew/homebrew-cask/pull/173061

**Comment by setchy** [comment]
Cask changes have been merged https://github.com/Homebrew/homebrew-cask/pull/173061

Will close after our next release

**Comment by setchy** [comment]
Tested successfully with v5.6.0 brew cask update
