### ISSUE TITLE
v5 loads forever

### ISSUE THREAD

**Issue by nihaals** [gitify-app/gitify#940]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

When using v5.0.0 or v5.1.0, Gitify loads forever and shows no notifications. When checking the API requests it's making, it seems to be working as expected with no more in-progress API requests.

### 🪜 Steps To Reproduce

1. Open Gitify
2. Notice no notifications are shown and the loading bar stays on
3. Install v4.6.1
4. Notice it works as expected

### ℹ System Info

```Markdown
- macOS 14.4.1
- Gitify 5.1.0
```

### 📸 Screenshots

https://github.com/gitify-app/gitify/assets/18350092/b80926c0-fd31-45ad-8070-ad6b62c20263

**Comment by setchy** [comment]
hi @nihaals - thanks for reporting.  

A few questions to help triage
* are you using GitHub, GitHub Enterprise or both? 
* are you able to check if your token has the `repo:scope` permission?  I believe you might be able to see this on the Gitify `Settings` screen

**Comment by nihaals** [comment]
I'm using GitHub.com and singing in with a PAT with the `repo` scope.

**Comment by setchy** [comment]
@nihaals - we shipped v5.2.0 earlier today. Would you mind confirming if this is still happening with that release please

**Comment by setchy** [comment]
@nihaals - very interested in solving this for you.

Can you confirm your PAT works when calling /notifications via Postman/curl?

Have you tried creating a new PAT using the steps in our `Login with Personal Access Token` screen?

PS - I also sent you an email to the address I'm your GH profile

**Comment by nihaals** [comment]
> Can you confirm your PAT works when calling /notifications via Postman/curl?

Reinstalling v4.6.1 with no config changes works fine and GitHub returns the expected response to `/notifications` when Gitify v5 calls it.

> Have you tried creating a new PAT using the steps in our `Login with Personal Access Token` screen?

I haven't but since Gitify is receiving a GitHub response as expected and v4 works I don't think this is it.

> PS - I also sent you an email to the address I'm your GH profile

I did reply although from a different email so you might have missed it.

**Comment by setchy** [comment]
@nihaals - we've just shipping v5.3.0.  Would appreciate to hear about your experience with this version...

**Comment by nihaals** [comment]
v5.3.0 fixed it!

**Comment by setchy** [comment]
> v5.3.0 fixed it!

phew!  thanks for confirming @nihaals
