### ISSUE TITLE
Bad credentials after clicking on PR title

### ISSUE THREAD

**Issue by MichalMichalak** [gitify-app/gitify#944]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### 📝 Description

I'm using Gitify with personal token and GitHub Enterprise. I've added rights to `user:read`, `repo`, `notofication` as instructed on login screen. When I login, Gitify properly shows the PRs. When I click on PR title, it disappears from the list only to show up some time later. At the same time I can see failed request in console.

```
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/enterprise-server@3.9/rest"
}
```

### 🪜 Steps To Reproduce

1. Use GH Enterprise, login and create personal access token with `user:read`, `repo`, `notofication` rights.
2. Use Gitify and login with the token.
3. Wait for PR appear on list.
4. Click PR title.

### Gitify Version

5.1.0

### Operating System

macOS

### GitHub Account

GitHub Enterprise

**Comment by afonsojramos** [comment]
I believe we currently do not support login with token for GitHub Enterprise. If you notice, through that method, you don't even provide the hostname. So you'll probably need to login using the ClientSecret method listed here: https://docs.github.com/en/enterprise-server@3.9/rest/authentication/authenticating-to-the-rest-api?apiVersion=2022-11-28#using-basic-authentication
<img width="612" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/0c3148d2-3609-42ae-a085-f74b6aa99273">

**Comment by MichalMichalak** [comment]
I may be wrong but... 🤔 

![Screenshot 2024-04-01 at 18 28 06](https://github.com/gitify-app/gitify/assets/3244285/60ad6e1b-61e0-45f4-8918-1edc089ff68b)

![Screenshot 2024-04-01 at 18 28 16](https://github.com/gitify-app/gitify/assets/3244285/8d1580e6-43e8-4362-8319-799774c266b3)

It worked for me till very recently. Granted, there were auth improvements in my organization recently and there is a chance that the API fails because of this but it doesn't look so according to my current knowledge. I will certainly close this issue if that's the case.

Besides, I can log in and Gitify pulls the list of PRs, so it must be working. At least partially.

**Comment by afonsojramos** [comment]
Whoops, not a morning person and still waking up here, you're totally right!

Then I am not really sure how you can have bad credentials while being able to fetch the list of PRs.
Might it be the link that is broken? Since it is when you click it that it breaks? Can you debug a bit on your side? Running a local build and adding a few console logs in the NotificationRow component would help

**Comment by setchy** [comment]
@MichalMichalak does this happen when clicking on all PR titles, or only specific types (if so, which ones).

**Comment by kpurdon** [comment]
This is happening for me as well. For me it's all "review requested" types, however i haven't had others yet to try.

**Comment by setchy** [comment]
Thanks @kpurdon for also confirming.

The heart of the title hyperlink logic is within
https://github.com/gitify-app/gitify/blob/d809809c0ac837be9ec0d91efe10b05d43984e10/src/utils/helpers.ts#L242

For Notification with `reason: review_requested` (ie: `type: PullRequest`), Gitify is following this logic:

1. If the notification has a `subject.latest_comment_url` value, follow it and use the `html_url` response value
2. If the notification has a `subject.url` value, follow it and use the `html_url` response value
3. Fallback to the notification `repository.html_url`

I think I know why this may be failing.  

@kpurdon or @MichalMichalak - would you be able to confirm the structure of the subject values `latest_comment_url` or `url`.  Are they in the format `https://api.github.com/repos/<org>/<repo>/pulls/<no>`, or `https://github.com/api/v3/repos/<org>/<repo>/pulls/<no>`?

**Comment by kpurdon** [comment]
They are `api.{hostname}.com/repos/{org}/{repo}/pulls/{number}` for me. FWIW the notification for the above comment worked fine.

**Comment by setchy** [comment]
> They are `api.{hostname}.com/repos/{org}/{repo}/pulls/{number}` for me. FWIW the notification for the above comment worked fine.

Thanks @kpurdon.  By chance, what happens when you call this endpoint with your token, do you get a valid API response containing the `html_url` attribute?

**Comment by kpurdon** [comment]
Alright, looks like it was some missing permissions on the token that caused that endpoint to fail. After adding permissions (not totally sure which one) that endpoint works. Waiting on another notification to come in to validate.

**Comment by MichalMichalak** [comment]
Now I've noticed. When you look at the screenshot, you can see two requests to the same URL - first fails, second one 3 lines below - succeeds. First is the result of click, the second gets PRs to populate the list.

When I compared curl of both, turns out that failing one's passes null as token in the header:
```
-H 'authorization: token null'
```
while the succeeding one passes actual token:
```
-H 'authorization: token ghp_r...K' \
```

Could that be the reason?

**Comment by setchy** [comment]
@MichalMichalak - incredibly helpful, thank you very much. This helps give us an idea of where we need to fix. I'll take a closer look in the morning. Appreciate it.

**Comment by setchy** [comment]
@MichalMichalak - I have a build available containing a (hopeful) fix.  If you have a moment, could you kindly test it and see if that resolves the token issue - https://github.com/gitify-app/gitify/actions/runs/8521007314

**Comment by MichalMichalak** [comment]
It solved my issue 🎉 Thank you

**Comment by setchy** [comment]
> It solved my issue 🎉 Thank you

Excellent! We'll get a new release out shortly
