### ISSUE TITLE
Filter notifications by Organization/User

### ISSUE THREAD

**Issue by afonsojramos** [gitify-app/gitify#979]
### 📝 Provide a description of the new feature

Similar to Github, we could have logos in the sidebar to filter by organization. Yes, it wouldn't have the same value as GitHub, but we already group by repo, so I suppose the value is already there.

<table>
<tr>
 <td>GitHub UI
 <td>Gitify sidebar
<tr>
 <td><img width="285" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/d8aae46e-b84a-4d34-b059-8ff0754a7006">
 <td><img width="70" alt="image" src="https://github.com/gitify-app/gitify/assets/19473034/f4a1b0aa-38b8-4bbe-a9c1-1bee9624281f">
</table>

**Comment by setchy** [comment]
Now that we have collapsible headers, I wonder if we can achieve something close to this by adding a notification count badge to our headers (account and repository)

**Comment by setchy** [comment]
Something like this (or similar)... 

<img width="498" alt="Screenshot 2024-06-19 at 11 56 09 AM" src="https://github.com/gitify-app/gitify/assets/386277/24d4a3b5-8c26-40b4-9f6d-9571e5060f48">
