### ISSUE TITLE
[Feature request] Keyboard shortcut to open the app

### ISSUE THREAD

**Issue by adufr** [gitify-app/gitify#995]
### 📝 Provide a description of the new feature

As a keyboard poweruser, I would like to be able to open/close the app with a keyboard shortcut (preferably customizable, can be disabled by default) to avoid using my trackpad/mouse.

### ➕ Additional Information

I didn't try it for now, but I think this is possible using [electron global shortcuts API](https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts#global-shortcuts)

If you think this could be a new feature, I'd like to work on it 😁

**Comment by afonsojramos** [comment]
For sure a useful one! Yeah, feel free to work on it!
